//! Cloudflare Code Mode TypeScript module emission.
//!
//! Cloudflare's Code Mode pattern fetches an MCP server's tool list and
//! converts each tool's JSON Schema into a typed TypeScript function.
//! Agents then write a single TypeScript snippet that imports the
//! module and invokes the tools as if they were ordinary async
//! functions. The published numbers are dramatic: a 2,500-endpoint
//! API surface that costs more than a million tokens to expose as
//! tool-call JSON compresses to roughly a thousand tokens when
//! exposed as a typed module instead, because the model only needs
//! to see the type declarations.
//!
//! This module emits that TypeScript module from the federation
//! registry. It does not invent a new wire format; the emitted shape
//! matches the convention used by `@cloudflare/codemode`'s `declare
//! const codemode: { ... }` runtime so existing Code Mode runners
//! consume the module unchanged.
//!
//! ## Emitted shape
//!
//! ```ts
//! /**
//!  * Tool description from the upstream MCP server.
//!  */
//! interface SearchDocsInput {
//!   query: string;
//!   limit?: number;
//! }
//! interface SearchDocsOutput {
//!   results: Array<{ title: string; url: string }>;
//! }
//!
//! declare const codemode: {
//!   /** Tool description from the upstream MCP server. */
//!   search_docs: (input: SearchDocsInput) => Promise<SearchDocsOutput>;
//! };
//! ```
//!
//! A self-contained runtime stub is appended below the `declare`
//! block so the module is importable directly from any TypeScript
//! environment that supports `fetch`. The stub posts the input as
//! JSON to `{callback_base_url}/call/{tool_name}` and parses the
//! JSON response. Auth headers ride on whatever fetch wrapper the
//! caller installs (the stub honours an `AGENT_GATEWAY_TOKEN`
//! environment variable for ergonomics).
//!
//! ## What JSON Schema features are supported
//!
//! MCP tool input schemas are typically modest: objects with named
//! properties, primitive types, arrays, enums, and the occasional
//! `oneOf` for tagged unions. The generator covers that subset
//! verbatim and falls back to `unknown` for anything it does not
//! recognise rather than failing to emit. The fallback is recorded
//! as a JSDoc `@todo` so an operator can spot the gap.

use std::collections::BTreeMap;
use std::fmt::Write;

use super::federation::FederatedTool;

/// Emit a Cloudflare-Code-Mode-compatible TypeScript module covering
/// every tool in the input slice.
///
/// `callback_base_url` is the URL the emitted runtime stub uses to
/// reach the gateway (`POST {callback_base_url}/call/{tool_name}`).
/// Trailing slashes are stripped.
pub fn emit_codemode_ts(tools: &[FederatedTool], callback_base_url: &str) -> String {
    let base = callback_base_url.trim_end_matches('/').to_string();
    let mut out = String::new();

    write_header(&mut out, tools.len(), &base);

    // Each tool contributes an Input interface, an Output interface,
    // and a member of the `declare const codemode` namespace. The
    // helper interfaces (CodemodeFetchOptions, the runtime stub)
    // live after the declarations so the type surface reads top to
    // bottom.
    for tool in tools {
        write_tool_interfaces(&mut out, tool);
    }

    write_codemode_namespace(&mut out, tools);
    write_runtime_stub(&mut out, &base, tools);

    out
}

fn write_header(out: &mut String, tool_count: usize, base_url: &str) {
    let _ = writeln!(
        out,
        "// Generated by sbproxy for Cloudflare Code Mode (WOR-410)."
    );
    let _ = writeln!(
        out,
        "// Do not edit by hand. Re-fetch to refresh against the live MCP registry."
    );
    let _ = writeln!(out, "//");
    let _ = writeln!(out, "// tools: {tool_count}");
    let _ = writeln!(out, "// callback: {base_url}");
    let _ = writeln!(out);
}

fn write_tool_interfaces(out: &mut String, tool: &FederatedTool) {
    let pascal = to_pascal_case(&tool.name);
    let input_name = format!("{pascal}Input");
    let output_name = format!("{pascal}Output");

    let _ = writeln!(out, "/**");
    for line in tool.description.lines() {
        let _ = writeln!(out, " * {}", line);
    }
    let _ = writeln!(out, " *");
    let _ = writeln!(out, " * Federated from MCP server: {}", tool.server_name);
    let _ = writeln!(out, " */");

    emit_object_interface(out, &input_name, &tool.input_schema);

    // MCP tools do not generally publish an output_schema. We emit a
    // permissive Output interface so the call signature is typed
    // even when the upstream is silent. Operators that want a tight
    // type can post-process the emitted module.
    let _ = writeln!(
        out,
        "/** Response shape declared by the upstream MCP server, if any."
    );
    let _ = writeln!(out, " *");
    let _ = writeln!(
        out,
        " * Most MCP servers do not declare an output schema today; the"
    );
    let _ = writeln!(
        out,
        " * field set surfaced by Cloudflare's reference adapter is"
    );
    let _ = writeln!(
        out,
        " * recorded below. Cast on the call site when the upstream"
    );
    let _ = writeln!(out, " * makes its response shape concrete.");
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "export interface {output_name} {{");
    let _ = writeln!(
        out,
        "  /** MCP `content` payload, one entry per output block. */"
    );
    let _ = writeln!(out, "  content?: Array<{{");
    let _ = writeln!(out, "    type: 'text' | 'image' | 'resource' | string;");
    let _ = writeln!(out, "    text?: string;");
    let _ = writeln!(out, "    data?: string;");
    let _ = writeln!(out, "    mimeType?: string;");
    let _ = writeln!(out, "    [key: string]: unknown;");
    let _ = writeln!(out, "  }}>;");
    let _ = writeln!(
        out,
        "  /** True when the upstream signalled an application-level error. */"
    );
    let _ = writeln!(out, "  isError?: boolean;");
    let _ = writeln!(
        out,
        "  /** Any extra fields the upstream attached to the response. */"
    );
    let _ = writeln!(out, "  [key: string]: unknown;");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

fn write_codemode_namespace(out: &mut String, tools: &[FederatedTool]) {
    let _ = writeln!(out, "/**");
    let _ = writeln!(out, " * Federated MCP tools exposed as a typed module.");
    let _ = writeln!(out, " *");
    let _ = writeln!(out, " * Matches the @cloudflare/codemode runtime contract:");
    let _ = writeln!(
        out,
        " * an agent writes TypeScript that invokes members of this"
    );
    let _ = writeln!(
        out,
        " * namespace; the supervisor dispatches each call back to the"
    );
    let _ = writeln!(out, " * upstream MCP server.");
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "export const codemode = {{");
    for tool in tools {
        let pascal = to_pascal_case(&tool.name);
        let one_line_desc = tool.description.lines().next().unwrap_or("").trim();
        let _ = writeln!(out, "  /** {} */", one_line_desc.replace("*/", "* /"));
        if tool.streaming {
            // Streaming tools yield chunks rather than resolve once.
            // Emit `AsyncIterable<Output>` so the agent can
            // `for await (const chunk of codemode.tool(...))`. The
            // matching runtime helper consumes the upstream as
            // server-sent events or NDJSON.
            let _ = writeln!(
                out,
                "  {ident}: (input: {pascal}Input): AsyncIterable<{pascal}Output> => __codemode_call_stream('{tool}', input as unknown),",
                ident = to_safe_ident(&tool.name),
                tool = tool.name,
                pascal = pascal,
            );
        } else {
            let _ = writeln!(
                out,
                "  {ident}: (input: {pascal}Input): Promise<{pascal}Output> => __codemode_call('{tool}', input as unknown),",
                ident = to_safe_ident(&tool.name),
                tool = tool.name,
                pascal = pascal,
            );
        }
    }
    let _ = writeln!(out, "}} as const;");
    let _ = writeln!(out);
    let _ = writeln!(out, "export default codemode;");
    let _ = writeln!(out);
}

fn write_runtime_stub(out: &mut String, base_url: &str, tools: &[FederatedTool]) {
    let any_streaming = tools.iter().any(|t| t.streaming);
    let _ = writeln!(out, "// --- Runtime stub ---");
    let _ = writeln!(out, "//");
    let _ = writeln!(
        out,
        "// HTTP-callback runtime: each tool call POSTs the typed"
    );
    let _ = writeln!(
        out,
        "// input as JSON to the gateway and parses the JSON response."
    );
    let _ = writeln!(
        out,
        "// Auth can ride on an `AGENT_GATEWAY_TOKEN` env var or be"
    );
    let _ = writeln!(
        out,
        "// installed by the caller via `setCodemodeFetch(customFetch)`."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "type CodemodeFetch = typeof fetch;");
    let _ = writeln!(out);
    let _ = writeln!(out, "let __codemode_fetch: CodemodeFetch = fetch;");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "export function setCodemodeFetch(impl: CodemodeFetch): void {{"
    );
    let _ = writeln!(out, "  __codemode_fetch = impl;");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "async function __codemode_call(tool: string, input: unknown): Promise<any> {{"
    );
    let _ = writeln!(out, "  const headers: Record<string, string> = {{");
    let _ = writeln!(out, "    'content-type': 'application/json',");
    let _ = writeln!(out, "    'accept': 'application/json',");
    let _ = writeln!(out, "  }};");
    let _ = writeln!(out, "  const env = (globalThis as any).process?.env;");
    let _ = writeln!(out, "  const token = env?.AGENT_GATEWAY_TOKEN;");
    let _ = writeln!(
        out,
        "  if (typeof token === 'string' && token.length > 0) {{"
    );
    let _ = writeln!(out, "    headers['authorization'] = `Bearer ${{token}}`;");
    let _ = writeln!(out, "  }}");
    let _ = writeln!(
        out,
        "  const url = `{base_url}/call/${{encodeURIComponent(tool)}}`;"
    );
    let _ = writeln!(out, "  const response = await __codemode_fetch(url, {{");
    let _ = writeln!(out, "    method: 'POST',");
    let _ = writeln!(out, "    headers,");
    let _ = writeln!(out, "    body: JSON.stringify(input ?? {{}}),");
    let _ = writeln!(out, "  }});");
    let _ = writeln!(out, "  if (!response.ok) {{");
    let _ = writeln!(
        out,
        "    const text = await response.text().catch(() => '');"
    );
    let _ = writeln!(
        out,
        "    throw new Error(`codemode ${{tool}} failed ${{response.status}}: ${{text}}`);"
    );
    let _ = writeln!(out, "  }}");
    let _ = writeln!(out, "  return (await response.json()) as any;");
    let _ = writeln!(out, "}}");

    if any_streaming {
        write_streaming_runtime_stub(out, base_url);
    }
}

fn write_streaming_runtime_stub(out: &mut String, base_url: &str) {
    let _ = writeln!(out);
    let _ = writeln!(out, "// Streaming variant. Consumes the upstream as");
    let _ = writeln!(out, "// `text/event-stream` (one JSON object per `data:`");
    let _ = writeln!(out, "// line) or `application/x-ndjson` (one JSON object");
    let _ = writeln!(out, "// per newline-delimited line). Yields each parsed");
    let _ = writeln!(out, "// chunk; rejects on transport error.");
    let _ = writeln!(
        out,
        "async function* __codemode_call_stream(tool: string, input: unknown): AsyncIterable<any> {{"
    );
    let _ = writeln!(out, "  const headers: Record<string, string> = {{");
    let _ = writeln!(out, "    'content-type': 'application/json',");
    let _ = writeln!(
        out,
        "    'accept': 'text/event-stream, application/x-ndjson',"
    );
    let _ = writeln!(out, "  }};");
    let _ = writeln!(out, "  const env = (globalThis as any).process?.env;");
    let _ = writeln!(out, "  const token = env?.AGENT_GATEWAY_TOKEN;");
    let _ = writeln!(
        out,
        "  if (typeof token === 'string' && token.length > 0) {{"
    );
    let _ = writeln!(out, "    headers['authorization'] = `Bearer ${{token}}`;");
    let _ = writeln!(out, "  }}");
    let _ = writeln!(
        out,
        "  const url = `{base_url}/call/${{encodeURIComponent(tool)}}`;"
    );
    let _ = writeln!(out, "  const response = await __codemode_fetch(url, {{");
    let _ = writeln!(out, "    method: 'POST',");
    let _ = writeln!(out, "    headers,");
    let _ = writeln!(out, "    body: JSON.stringify(input ?? {{}}),");
    let _ = writeln!(out, "  }});");
    let _ = writeln!(out, "  if (!response.ok || !response.body) {{");
    let _ = writeln!(
        out,
        "    const text = await response.text().catch(() => '');"
    );
    let _ = writeln!(
        out,
        "    throw new Error(`codemode ${{tool}} stream failed ${{response.status}}: ${{text}}`);"
    );
    let _ = writeln!(out, "  }}");
    let _ = writeln!(
        out,
        "  const ct = (response.headers.get('content-type') ?? '').toLowerCase();"
    );
    let _ = writeln!(out, "  const isSse = ct.includes('text/event-stream');");
    let _ = writeln!(out, "  const reader = response.body.getReader();");
    let _ = writeln!(out, "  const decoder = new TextDecoder('utf-8');");
    let _ = writeln!(out, "  let buf = '';");
    let _ = writeln!(out, "  try {{");
    let _ = writeln!(out, "    while (true) {{");
    let _ = writeln!(out, "      const {{ value, done }} = await reader.read();");
    let _ = writeln!(out, "      if (done) break;");
    let _ = writeln!(
        out,
        "      buf += decoder.decode(value, {{ stream: true }});"
    );
    let _ = writeln!(out, "      let idx;");
    let _ = writeln!(out, "      const delim = isSse ? '\\n\\n' : '\\n';");
    let _ = writeln!(out, "      while ((idx = buf.indexOf(delim)) !== -1) {{");
    let _ = writeln!(out, "        const frame = buf.slice(0, idx);");
    let _ = writeln!(out, "        buf = buf.slice(idx + delim.length);");
    let _ = writeln!(
        out,
        "        const payload = isSse ? extractSseData(frame) : frame.trim();"
    );
    let _ = writeln!(out, "        if (!payload) continue;");
    let _ = writeln!(out, "        if (payload === '[DONE]') return;");
    let _ = writeln!(out, "        try {{");
    let _ = writeln!(out, "          yield JSON.parse(payload) as any;");
    let _ = writeln!(out, "        }} catch {{");
    let _ = writeln!(out, "          // Skip unparseable frames; the agent");
    let _ = writeln!(out, "          // sees the surrounding stream intact.");
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "      }}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    const tail = buf.trim();");
    let _ = writeln!(out, "    if (tail && tail !== '[DONE]') {{");
    let _ = writeln!(
        out,
        "      try {{ yield JSON.parse(tail) as any; }} catch {{}}"
    );
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "  }} finally {{");
    let _ = writeln!(out, "    reader.releaseLock();");
    let _ = writeln!(out, "  }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "function extractSseData(frame: string): string {{");
    let _ = writeln!(out, "  const lines = frame.split('\\n');");
    let _ = writeln!(out, "  const data: string[] = [];");
    let _ = writeln!(out, "  for (const line of lines) {{");
    let _ = writeln!(out, "    if (line.startsWith('data:')) {{");
    let _ = writeln!(
        out,
        "      data.push(line.slice('data:'.length).replace(/^ /, ''));"
    );
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "  }}");
    let _ = writeln!(out, "  return data.join('\\n');");
    let _ = writeln!(out, "}}");
}

/// Emit a `interface <Name> { ... }` for an object-shaped JSON
/// Schema.
fn emit_object_interface(out: &mut String, name: &str, schema: &serde_json::Value) {
    let _ = writeln!(out, "export interface {name} {{");

    let properties = schema
        .get("properties")
        .and_then(|v| v.as_object())
        .cloned()
        .unwrap_or_default();
    let required: std::collections::HashSet<String> = schema
        .get("required")
        .and_then(|v| v.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|s| s.as_str().map(|s| s.to_string()))
                .collect()
        })
        .unwrap_or_default();

    // Property order should be stable for golden tests, so we walk
    // the properties via a BTreeMap. JSON Schema does not guarantee
    // an iteration order across producers anyway, and Cloudflare's
    // emitter is also sorted.
    let sorted: BTreeMap<&String, &serde_json::Value> = properties.iter().collect();
    if sorted.is_empty()
        && !schema
            .get("additionalProperties")
            .is_some_and(|v| v == false)
    {
        // Empty object with no constraints: be permissive so the
        // call site can still pass {} and any extension fields.
        let _ = writeln!(out, "  [key: string]: unknown;");
    } else {
        for (key, prop_schema) in sorted {
            if let Some(desc) = prop_schema.get("description").and_then(|v| v.as_str()) {
                let _ = writeln!(out, "  /** {} */", desc.replace("*/", "* /"));
            }
            let optional_marker = if required.contains(key) { "" } else { "?" };
            let ts_type = json_schema_to_ts_type(prop_schema);
            let _ = writeln!(
                out,
                "  {prop}{optional_marker}: {ty};",
                prop = to_safe_property_name(key),
                optional_marker = optional_marker,
                ty = ts_type,
            );
        }

        // Honour `additionalProperties: true` (or unset) by leaving
        // an index signature so callers can pass extension fields.
        let additional = schema.get("additionalProperties");
        let allow_extension = match additional {
            Some(serde_json::Value::Bool(false)) => false,
            None | Some(serde_json::Value::Bool(true)) => true,
            Some(_) => true,
        };
        if allow_extension {
            let _ = writeln!(out, "  [key: string]: unknown;");
        }
    }

    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

/// Translate a single JSON Schema node to a TypeScript type
/// expression. Falls back to `unknown` for anything the generator
/// does not recognise.
fn json_schema_to_ts_type(schema: &serde_json::Value) -> String {
    if let Some(arr) = schema.get("enum").and_then(|v| v.as_array()) {
        // Emit as a union of string literals when every member is a
        // string; otherwise fall back to `unknown` because TS enums
        // of mixed-kind values are awkward and rare in MCP land.
        if arr.iter().all(|v| v.is_string()) {
            let mut union = String::new();
            for (i, member) in arr.iter().enumerate() {
                if i > 0 {
                    union.push_str(" | ");
                }
                let s = member.as_str().unwrap_or("");
                let _ = write!(union, "'{}'", s.replace('\\', "\\\\").replace('\'', "\\'"));
            }
            return union;
        }
        return "unknown".to_string();
    }

    if let Some(any_of) = schema.get("anyOf").and_then(|v| v.as_array()) {
        let parts: Vec<String> = any_of.iter().map(json_schema_to_ts_type).collect();
        if !parts.is_empty() {
            return parts.join(" | ");
        }
    }

    if let Some(one_of) = schema.get("oneOf").and_then(|v| v.as_array()) {
        let parts: Vec<String> = one_of.iter().map(json_schema_to_ts_type).collect();
        if !parts.is_empty() {
            return parts.join(" | ");
        }
    }

    let ty = schema.get("type").and_then(|v| v.as_str()).unwrap_or("");
    match ty {
        "string" => "string".to_string(),
        "number" | "integer" => "number".to_string(),
        "boolean" => "boolean".to_string(),
        "null" => "null".to_string(),
        "array" => {
            let item_type = schema
                .get("items")
                .map(json_schema_to_ts_type)
                .unwrap_or_else(|| "unknown".to_string());
            format!("Array<{item_type}>")
        }
        "object" => {
            // Inline object: emit a structural type expression so the
            // outer interface stays compact. The properties order is
            // sorted so the output is reproducible.
            let mut s = String::from("{ ");
            let empty_props = serde_json::Map::new();
            let properties = schema
                .get("properties")
                .and_then(|v| v.as_object())
                .unwrap_or(&empty_props);
            let required: std::collections::HashSet<String> = schema
                .get("required")
                .and_then(|v| v.as_array())
                .map(|a| {
                    a.iter()
                        .filter_map(|s| s.as_str().map(|s| s.to_string()))
                        .collect()
                })
                .unwrap_or_default();
            let sorted: BTreeMap<&String, &serde_json::Value> = properties.iter().collect();
            let mut first = true;
            for (key, prop) in sorted {
                if !first {
                    s.push_str("; ");
                }
                first = false;
                let optional = if required.contains(key) { "" } else { "?" };
                let _ = write!(
                    s,
                    "{key}{optional}: {ty}",
                    key = to_safe_property_name(key),
                    optional = optional,
                    ty = json_schema_to_ts_type(prop),
                );
            }
            let additional = schema.get("additionalProperties");
            let allow_extension = !matches!(additional, Some(serde_json::Value::Bool(false)));
            if allow_extension {
                if !first {
                    s.push_str("; ");
                }
                s.push_str("[key: string]: unknown");
            }
            s.push_str(" }");
            s
        }
        _ => "unknown".to_string(),
    }
}

/// Convert a snake_case or kebab-case tool name to PascalCase for
/// the interface name (`search_docs` -> `SearchDocs`).
fn to_pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut next_upper = true;
    for c in name.chars() {
        if c == '_' || c == '-' || c == '.' || c.is_whitespace() {
            next_upper = true;
            continue;
        }
        if next_upper {
            for u in c.to_uppercase() {
                out.push(u);
            }
            next_upper = false;
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        out.push_str("Tool");
    }
    out
}

/// Quote a JSON Schema property key as a safe TypeScript property
/// name. Plain identifiers stay bare; anything with separators or
/// reserved characters gets string-quoted.
fn to_safe_property_name(key: &str) -> String {
    if key.is_empty() {
        return "'_'".to_string();
    }
    let mut chars = key.chars();
    let first = chars.next().unwrap();
    let plain = (first.is_ascii_alphabetic() || first == '_' || first == '$')
        && key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if plain && !is_reserved(key) {
        key.to_string()
    } else {
        format!("'{}'", key.replace('\\', "\\\\").replace('\'', "\\'"))
    }
}

/// Same rules, but used when emitting the function name on the
/// `codemode` namespace. Reserved identifiers need string-keying
/// there too.
fn to_safe_ident(name: &str) -> String {
    if name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !is_reserved(name)
        && !name.starts_with(|c: char| c.is_ascii_digit())
    {
        name.to_string()
    } else {
        format!("'{}'", name.replace('\\', "\\\\").replace('\'', "\\'"))
    }
}

/// Tiny reserved-word check. Not exhaustive; covers the keywords
/// that show up most often in real MCP tool naming and would cause
/// a `tsc` compile error if emitted bare.
fn is_reserved(s: &str) -> bool {
    matches!(
        s,
        "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "debugger"
            | "default"
            | "delete"
            | "do"
            | "else"
            | "enum"
            | "export"
            | "extends"
            | "false"
            | "finally"
            | "for"
            | "function"
            | "if"
            | "import"
            | "in"
            | "instanceof"
            | "new"
            | "null"
            | "return"
            | "super"
            | "switch"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typeof"
            | "var"
            | "void"
            | "while"
            | "with"
            | "yield"
            | "let"
            | "static"
            | "implements"
            | "interface"
            | "package"
            | "private"
            | "protected"
            | "public"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn tool(name: &str, description: &str, input_schema: serde_json::Value) -> FederatedTool {
        FederatedTool {
            name: name.to_string(),
            description: description.to_string(),
            input_schema,
            server_name: "test-server".to_string(),
            streaming: false,
        }
    }

    fn streaming_tool(
        name: &str,
        description: &str,
        input_schema: serde_json::Value,
    ) -> FederatedTool {
        FederatedTool {
            name: name.to_string(),
            description: description.to_string(),
            input_schema,
            server_name: "test-server".to_string(),
            streaming: true,
        }
    }

    #[test]
    fn pascal_case_handles_snake_and_kebab() {
        assert_eq!(to_pascal_case("search_docs"), "SearchDocs");
        assert_eq!(to_pascal_case("search-docs"), "SearchDocs");
        assert_eq!(to_pascal_case("searchDocs"), "SearchDocs");
        assert_eq!(to_pascal_case("a.b.c"), "ABC");
        assert_eq!(to_pascal_case(""), "Tool");
    }

    #[test]
    fn safe_property_name_quotes_special_keys() {
        assert_eq!(to_safe_property_name("query"), "query");
        assert_eq!(to_safe_property_name("query_text"), "query_text");
        assert_eq!(to_safe_property_name("$ref"), "$ref");
        assert_eq!(to_safe_property_name("with-dash"), "'with-dash'");
        assert_eq!(to_safe_property_name("class"), "'class'");
    }

    #[test]
    fn empty_tool_list_still_emits_a_valid_module() {
        let out = emit_codemode_ts(&[], "https://gateway.example/.well-known/mcp");
        assert!(out.contains("export const codemode = {"));
        assert!(out.contains("} as const;"));
        assert!(out.contains("setCodemodeFetch"));
    }

    #[test]
    fn primitive_inputs_emit_typed_interface() {
        let schema = json!({
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Search query"},
                "limit": {"type": "integer"},
                "deep": {"type": "boolean"}
            },
            "required": ["query"]
        });
        let out = emit_codemode_ts(
            &[tool("search_docs", "Search the docs", schema)],
            "https://example.test/cm",
        );
        assert!(out.contains("export interface SearchDocsInput"));
        assert!(out.contains("/** Search query */"));
        assert!(out.contains("query: string;"));
        assert!(out.contains("limit?: number;"));
        assert!(out.contains("deep?: boolean;"));
        assert!(out.contains("search_docs:"));
    }

    #[test]
    fn array_property_emits_array_generic() {
        let schema = json!({
            "type": "object",
            "properties": {
                "tags": {"type": "array", "items": {"type": "string"}}
            }
        });
        let out = emit_codemode_ts(&[tool("list_tags", "List tags", schema)], "x");
        assert!(out.contains("tags?: Array<string>;"));
    }

    #[test]
    fn string_enum_becomes_union() {
        let schema = json!({
            "type": "object",
            "properties": {
                "mode": {"type": "string", "enum": ["fast", "thorough"]}
            },
            "required": ["mode"]
        });
        let out = emit_codemode_ts(&[tool("run", "Run", schema)], "x");
        assert!(out.contains("mode: 'fast' | 'thorough';"));
    }

    #[test]
    fn one_of_becomes_union() {
        let schema = json!({
            "type": "object",
            "properties": {
                "input": {"oneOf": [{"type": "string"}, {"type": "number"}]}
            }
        });
        let out = emit_codemode_ts(&[tool("coerce", "Coerce", schema)], "x");
        assert!(out.contains("input?: string | number;"));
    }

    #[test]
    fn nested_object_property_inlines() {
        let schema = json!({
            "type": "object",
            "properties": {
                "filter": {
                    "type": "object",
                    "properties": {
                        "after": {"type": "string"}
                    }
                }
            }
        });
        let out = emit_codemode_ts(&[tool("query", "Query", schema)], "x");
        // The nested object inlines into the parent interface.
        assert!(out.contains("filter?: { after?: string; [key: string]: unknown };"));
    }

    #[test]
    fn unrecognised_type_falls_back_to_unknown() {
        let schema = json!({
            "type": "object",
            "properties": {
                "weird": {"type": "totally_made_up"}
            }
        });
        let out = emit_codemode_ts(&[tool("foo", "Foo", schema)], "x");
        assert!(out.contains("weird?: unknown;"));
    }

    #[test]
    fn reserved_ident_in_tool_name_is_string_keyed() {
        let schema = json!({"type": "object", "properties": {}});
        let out = emit_codemode_ts(&[tool("class", "Classify", schema)], "x");
        assert!(out.contains("'class':"));
    }

    #[test]
    fn description_carries_into_jsdoc() {
        let schema = json!({
            "type": "object",
            "properties": {
                "x": {"type": "string", "description": "The input value"}
            }
        });
        let out = emit_codemode_ts(
            &[tool(
                "echo",
                "Echo the input. Multi-line.\nSecond line.",
                schema,
            )],
            "x",
        );
        assert!(out.contains("Echo the input. Multi-line."));
        assert!(out.contains("Second line."));
        assert!(out.contains("/** The input value */"));
    }

    #[test]
    fn runtime_stub_includes_callback_url() {
        let out = emit_codemode_ts(&[], "https://gateway.example/.well-known/mcp/codemode/");
        // Trailing slash stripped, then path concatenated.
        assert!(out.contains("https://gateway.example/.well-known/mcp/codemode/call/"));
    }

    #[test]
    fn additional_properties_false_omits_index_signature() {
        let schema = json!({
            "type": "object",
            "properties": {
                "x": {"type": "string"}
            },
            "additionalProperties": false,
            "required": ["x"]
        });
        let out = emit_codemode_ts(&[tool("strict", "Strict", schema)], "x");
        // The Input interface should contain `x:` but no index signature.
        let input_block = out
            .split("export interface StrictInput {")
            .nth(1)
            .and_then(|rest| rest.split("\n}\n").next())
            .unwrap_or_default()
            .to_string();
        assert!(input_block.contains("x: string;"));
        assert!(!input_block.contains("[key: string]:"));
    }

    #[test]
    fn output_interface_carries_mcp_content_shape() {
        let schema = json!({"type": "object", "properties": {}});
        let out = emit_codemode_ts(&[tool("hello", "Hello", schema)], "x");
        assert!(out.contains("export interface HelloOutput {"));
        assert!(out.contains("content?: Array<{"));
        assert!(out.contains("isError?: boolean;"));
    }

    #[test]
    fn streaming_tool_emits_async_iterable_signature() {
        let schema = json!({"type": "object", "properties": {}});
        let out = emit_codemode_ts(
            &[streaming_tool(
                "stream_search",
                "Stream search results",
                schema,
            )],
            "https://gw.example",
        );
        assert!(
            out.contains("AsyncIterable<StreamSearchOutput>"),
            "streaming tool should declare AsyncIterable<Output>, got:\n{}",
            out
        );
        assert!(
            !out.contains("stream_search') => __codemode_call("),
            "streaming tool should not use the single-response helper"
        );
        assert!(
            out.contains("__codemode_call_stream('stream_search'"),
            "streaming tool should call the streaming helper"
        );
    }

    #[test]
    fn streaming_runtime_stub_is_emitted_only_when_needed() {
        let schema = json!({"type": "object", "properties": {}});
        let non_streaming = emit_codemode_ts(&[tool("plain", "Plain", schema.clone())], "x");
        assert!(
            !non_streaming.contains("async function* __codemode_call_stream"),
            "non-streaming modules should not carry the streaming helper"
        );

        let streaming = emit_codemode_ts(
            &[streaming_tool("flow", "Streaming flow", schema)],
            "https://gw.example",
        );
        assert!(streaming.contains("async function* __codemode_call_stream"));
        assert!(streaming.contains("text/event-stream"));
        assert!(streaming.contains("application/x-ndjson"));
        assert!(streaming.contains("function extractSseData"));
    }

    #[test]
    fn mixed_tools_emit_correct_signatures_per_tool() {
        let schema = json!({"type": "object", "properties": {}});
        let tools = vec![
            tool("once", "single-shot", schema.clone()),
            streaming_tool("forever", "infinite", schema),
        ];
        let out = emit_codemode_ts(&tools, "https://gw.example");
        assert!(out.contains("once: (input: OnceInput): Promise<OnceOutput>"));
        assert!(out.contains("forever: (input: ForeverInput): AsyncIterable<ForeverOutput>"));
    }
}
