FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata
COPY sbproxy /usr/local/bin/sbproxy
RUN mkdir -p /etc/sbproxy
VOLUME /etc/sbproxy
EXPOSE 8080/tcp
EXPOSE 8443/tcp
EXPOSE 8443/udp
ENTRYPOINT ["sbproxy"]
CMD ["serve", "-c", "/etc/sbproxy"]
