//! RFC 9421 HTTP Message Signatures: sign-on-egress.
//!
//! Companion to [`crate::signatures`], which implements the inbound
//! verification half. This module produces the `Content-Digest`,
//! `Signature-Input`, and `Signature` headers an outbound request
//! needs so a downstream verifier (the existing
//! [`MessageSignatureVerifier`](crate::signatures::MessageSignatureVerifier),
//! or any Web Bot Auth compatible origin) can confirm the request was
//! signed by the holder of the configured workspace key.
//!
//! [Web Bot Auth]: https://datatracker.ietf.org/doc/draft-meunier-web-bot-auth-architecture/
//!
//! # Scope
//!
//! - Algorithms: `ed25519` (primary, the Web Bot Auth profile) and
//!   `hmac-sha256` (secondary).
//! - Default covered components: `@method`, `@target-uri`, `@authority`,
//!   and `content-digest` when the request carries a body.
//! - Optional `Content-Digest` emission via
//!   [`compute_content_digest`](crate::digest::compute_content_digest)
//!   (RFC 9530 `sha-256` by default). If the request has a body and
//!   `content-digest` is in the covered set, the signer adds the header
//!   itself; this keeps the signed-payload binding intact even if the
//!   caller forgot to compute the digest.
//! - The `created` parameter is set to the current wall-clock time and
//!   the `keyid` + `alg` parameters reflect the
//!   [`SignerConfig`](crate::signatures_egress::SignerConfig).
//!
//! # What this module is not
//!
//! - Workspace key management. The signer takes the secret bytes
//!   verbatim; how the operator stores it (Vault, env, KMS) is a
//!   separate concern.
//! - Pingora outbound-hook wiring. This module is a pure function: in
//!   takes a `http::Request<bytes::Bytes>`, out comes the same request
//!   with three signature headers attached.
//!
//! # Example
//!
//! ```
//! use bytes::Bytes;
//! use sbproxy_middleware::signatures_egress::{MessageSigner, SignerConfig};
//! use sbproxy_middleware::signatures::SignatureAlgorithm;
//!
//! // Random Ed25519 key generated by the operator; in a real
//! // deployment this comes from workspace key material.
//! let secret = [0u8; 32];
//! let cfg = SignerConfig {
//!     key_id: "workspace-egress-1".to_string(),
//!     algorithm: SignatureAlgorithm::Ed25519,
//!     secret: secret.to_vec(),
//!     covered_components: Vec::new(), // empty = use defaults
//! };
//! let signer = MessageSigner::new(cfg).unwrap();
//!
//! let req = http::Request::builder()
//!     .method("POST")
//!     .uri("https://api.example.com/v1/items")
//!     .body(Bytes::from_static(b"{}"))
//!     .unwrap();
//! let signed = signer.sign_request(req).unwrap();
//! assert!(signed.headers().contains_key("signature"));
//! assert!(signed.headers().contains_key("signature-input"));
//! assert!(signed.headers().contains_key("content-digest"));
//! ```

use std::time::{SystemTime, UNIX_EPOCH};

use base64::Engine as _;
use bytes::Bytes;
use ed25519_dalek::{Signer as _, SigningKey};
use hmac::{Hmac, KeyInit, Mac};
use http::{header::HeaderName, HeaderValue, Request};
use sha2::Sha256;

use crate::digest::{compute_content_digest, Algorithm};
use crate::signatures::{build_signature_base, parse_signature_input, SignatureAlgorithm};

type HmacSha256 = Hmac<Sha256>;

/// Default covered components when [`SignerConfig::covered_components`]
/// is empty. Matches the Web Bot Auth profile's expected minimum
/// coverage set; `content-digest` is automatically dropped if the
/// request has no body.
pub const DEFAULT_COVERED_COMPONENTS: &[&str] =
    &["@method", "@target-uri", "@authority", "content-digest"];

/// Default signature label used in the `Signature-Input` / `Signature`
/// dictionaries. RFC 9421 allows any short token; `sig1` is the
/// canonical placeholder used throughout the RFC's examples.
pub const DEFAULT_SIGNATURE_LABEL: &str = "sig1";

// --- Config -----------------------------------------------------------

/// Configuration for an outbound RFC 9421 signer.
///
/// `secret` is interpreted per `algorithm`:
///
/// - [`SignatureAlgorithm::Ed25519`]: 32-byte raw seed (the private
///   half of the Ed25519 keypair).
/// - [`SignatureAlgorithm::HmacSha256`]: arbitrary-length shared
///   secret; HMAC-SHA256 hashes oversized keys and zero-pads short
///   ones per RFC 2104.
#[derive(Debug, Clone)]
pub struct SignerConfig {
    /// `keyid` parameter advertised on every signature. The verifier
    /// uses this string to look up the matching public key on its side.
    pub key_id: String,
    /// Signature algorithm. Drives both the wire-format `alg` parameter
    /// and the secret-decoding rules above.
    pub algorithm: SignatureAlgorithm,
    /// Raw secret bytes (see field-level docs for per-algorithm
    /// interpretation).
    pub secret: Vec<u8>,
    /// Covered components in the order they should appear in
    /// `Signature-Input`. An empty vector means "use
    /// [`DEFAULT_COVERED_COMPONENTS`]".
    pub covered_components: Vec<String>,
}

/// Errors produced by the signer.
#[derive(Debug)]
pub enum SignerError {
    /// The configured key material was the wrong shape for the
    /// algorithm (e.g. an Ed25519 secret that was not 32 bytes).
    InvalidKey(String),
    /// One of the covered components could not be resolved against the
    /// request (e.g. `@authority` with no host).
    SignatureBase(String),
    /// Building the headers produced bytes that are not a valid HTTP
    /// header value. Almost impossible in practice; surfaces as a
    /// distinct variant so callers can log it cleanly.
    InvalidHeaderValue(String),
}

impl std::fmt::Display for SignerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SignerError::InvalidKey(s) => write!(f, "invalid signer key: {s}"),
            SignerError::SignatureBase(s) => write!(f, "signature base construction failed: {s}"),
            SignerError::InvalidHeaderValue(s) => write!(f, "invalid header value: {s}"),
        }
    }
}

impl std::error::Error for SignerError {}

// --- Signer -----------------------------------------------------------

/// Outbound RFC 9421 signer.
///
/// Construct once from a [`SignerConfig`]; reuse across requests. The
/// signer keeps the decoded key material so the per-request path never
/// re-validates the secret shape.
pub struct MessageSigner {
    key_id: String,
    algorithm: SignatureAlgorithm,
    covered_components: Vec<String>,
    /// Decoded key material. For Ed25519 the signer holds the parsed
    /// `SigningKey`; for HMAC the raw secret bytes.
    key_material: KeyMaterial,
    /// Digest algorithm used when synthesising `Content-Digest`.
    /// Pinned to `sha-256` for now: it is the Web Bot Auth profile's
    /// default and the cheapest of the two RFC 9530 active algorithms.
    digest_algorithm: Algorithm,
    /// Signature label used in the `Signature-Input` / `Signature`
    /// dictionaries. Defaults to [`DEFAULT_SIGNATURE_LABEL`].
    signature_label: String,
    /// Optional `tag` parameter. The Web Bot Auth profile sets this to
    /// `web-bot-auth` so a verifier can scope the signature to that
    /// profile. `None` omits the parameter.
    tag: Option<String>,
    /// Optional signature lifetime in seconds. When set, each signature
    /// carries an `expires` parameter at `created + expires_secs`, after
    /// which a conforming verifier rejects it.
    expires_secs: Option<u64>,
}

enum KeyMaterial {
    Ed25519(SigningKey),
    HmacSha256(Vec<u8>),
}

impl std::fmt::Debug for MessageSigner {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MessageSigner")
            .field("key_id", &self.key_id)
            .field("algorithm", &self.algorithm)
            .field("covered_components", &self.covered_components)
            .field("digest_algorithm", &self.digest_algorithm)
            .field("signature_label", &self.signature_label)
            .field("tag", &self.tag)
            .field("expires_secs", &self.expires_secs)
            // Deliberately omit key_material so debug output never
            // accidentally surfaces the secret.
            .finish()
    }
}

impl MessageSigner {
    /// Build a signer, validating the key material up front so the
    /// per-request path can't fail on shape errors.
    pub fn new(config: SignerConfig) -> Result<Self, SignerError> {
        let SignerConfig {
            key_id,
            algorithm,
            secret,
            covered_components,
        } = config;

        let key_material = match algorithm {
            SignatureAlgorithm::Ed25519 => {
                let arr: [u8; 32] = secret.as_slice().try_into().map_err(|_| {
                    SignerError::InvalidKey(format!(
                        "ed25519 secret must be 32 bytes, got {}",
                        secret.len()
                    ))
                })?;
                KeyMaterial::Ed25519(SigningKey::from_bytes(&arr))
            }
            SignatureAlgorithm::HmacSha256 => {
                if secret.is_empty() {
                    return Err(SignerError::InvalidKey(
                        "hmac-sha256 secret must be non-empty".to_string(),
                    ));
                }
                KeyMaterial::HmacSha256(secret)
            }
        };

        let covered_components = if covered_components.is_empty() {
            DEFAULT_COVERED_COMPONENTS
                .iter()
                .map(|s| (*s).to_string())
                .collect()
        } else {
            covered_components
        };

        Ok(Self {
            key_id,
            algorithm,
            covered_components,
            key_material,
            digest_algorithm: Algorithm::Sha256,
            signature_label: DEFAULT_SIGNATURE_LABEL.to_string(),
            tag: None,
            expires_secs: None,
        })
    }

    /// Override the default signature label (`sig1`). Useful if the
    /// caller is layering multiple signatures on the same request.
    pub fn with_signature_label(mut self, label: impl Into<String>) -> Self {
        self.signature_label = label.into();
        self
    }

    /// Override the digest algorithm used when synthesising
    /// `Content-Digest`. Pinned to `sha-256` by default to match the
    /// Web Bot Auth profile.
    pub fn with_digest_algorithm(mut self, algorithm: Algorithm) -> Self {
        self.digest_algorithm = algorithm;
        self
    }

    /// Apply the Web Bot Auth signature profile: stamp a `tag` parameter
    /// (typically `web-bot-auth`) and an `expires` parameter set to
    /// `created + expires_secs`. A conforming verifier rejects the
    /// signature once `expires` passes, which bounds replay of a leaked
    /// outbound signature.
    pub fn with_web_bot_auth_profile(mut self, tag: impl Into<String>, expires_secs: u64) -> Self {
        self.tag = Some(tag.into());
        self.expires_secs = Some(expires_secs);
        self
    }

    /// Sign a request, returning a new request that carries the
    /// `Content-Digest` (when applicable), `Signature-Input`, and
    /// `Signature` headers.
    ///
    /// The request is consumed and returned by value so the signer can
    /// add a body-derived `Content-Digest` header without forcing the
    /// caller to mutate the request twice.
    pub fn sign_request(&self, mut req: Request<Bytes>) -> Result<Request<Bytes>, SignerError> {
        // Step 1: if the covered set includes content-digest and the
        // request has a body, make sure the header is present. We only
        // add it when it's missing so callers who pre-computed the
        // digest (perhaps via the streaming DigestSink) win.
        let wants_digest = self
            .covered_components
            .iter()
            .any(|c| c.eq_ignore_ascii_case("content-digest"));
        let has_body = !req.body().is_empty();
        let mut effective_components = self.covered_components.clone();

        if wants_digest {
            if has_body {
                if !req.headers().contains_key("content-digest") {
                    let header_value =
                        compute_content_digest(self.digest_algorithm, req.body().as_ref());
                    let value = HeaderValue::from_str(&header_value).map_err(|e| {
                        SignerError::InvalidHeaderValue(format!("content-digest: {e}"))
                    })?;
                    req.headers_mut().insert("content-digest", value);
                }
            } else {
                // RFC 9421 §2.1 only covers components that are present
                // on the message. Dropping the component on a bodyless
                // request is the right call; the alternative is to
                // bail out, which would be hostile to GET signers.
                effective_components.retain(|c| !c.eq_ignore_ascii_case("content-digest"));
            }
        }

        // Step 2: stamp the parameters.
        let created = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);

        // Step 3: build the canonical Signature-Input header value
        // first; we then re-parse it so the canonical base is built by
        // exactly the same code path the verifier uses.
        let expires = self
            .expires_secs
            .map(|secs| created.saturating_add(secs as i64));
        let signature_input_value = build_signature_input_header(
            &self.signature_label,
            &effective_components,
            &SignatureInputParams {
                created: Some(created),
                expires,
                keyid: self.key_id.clone(),
                alg: self.algorithm,
                tag: self.tag.clone(),
            },
        );

        // Re-parse via the existing inbound parser so raw_inner_list +
        // raw_params reflect exactly the byte sequence we just emitted.
        let parsed = parse_signature_input(&signature_input_value)
            .map_err(|e| SignerError::SignatureBase(format!("re-parse Signature-Input: {e}")))?;
        let (_, entry) = parsed
            .into_iter()
            .next()
            .ok_or_else(|| SignerError::SignatureBase("empty Signature-Input".to_string()))?;

        // Insert the Signature-Input header on the request before
        // building the base so any signer that decides to add
        // "signature-input" to its covered set in the future would
        // observe the live header.
        let sig_input_header = HeaderValue::from_str(&signature_input_value)
            .map_err(|e| SignerError::InvalidHeaderValue(format!("signature-input: {e}")))?;
        req.headers_mut()
            .insert(HeaderName::from_static("signature-input"), sig_input_header);

        // Build the canonical signature base using the same routine the
        // verifier will use on the inbound side; this is what
        // guarantees a round-trip match.
        let base = build_signature_base(&req, &entry)
            .map_err(|e| SignerError::SignatureBase(format!("build signature base: {e}")))?;

        // Step 4: run the crypto.
        let raw_sig = match &self.key_material {
            KeyMaterial::Ed25519(signing_key) => {
                signing_key.sign(base.as_bytes()).to_bytes().to_vec()
            }
            KeyMaterial::HmacSha256(secret) => {
                let mut mac = HmacSha256::new_from_slice(secret)
                    .map_err(|e| SignerError::InvalidKey(format!("hmac init: {e}")))?;
                mac.update(base.as_bytes());
                mac.finalize().into_bytes().to_vec()
            }
        };

        let sig_b64 = base64::engine::general_purpose::STANDARD.encode(&raw_sig);
        let sig_header_value = format!("{}=:{}:", self.signature_label, sig_b64);
        let sig_header = HeaderValue::from_str(&sig_header_value)
            .map_err(|e| SignerError::InvalidHeaderValue(format!("signature: {e}")))?;
        req.headers_mut()
            .insert(HeaderName::from_static("signature"), sig_header);

        Ok(req)
    }
}

// --- Wire-format builders --------------------------------------------

struct SignatureInputParams {
    created: Option<i64>,
    expires: Option<i64>,
    keyid: String,
    alg: SignatureAlgorithm,
    tag: Option<String>,
}

fn algorithm_wire_token(algorithm: SignatureAlgorithm) -> &'static str {
    match algorithm {
        SignatureAlgorithm::Ed25519 => "ed25519",
        SignatureAlgorithm::HmacSha256 => "hmac-sha256",
    }
}

/// Format a Signature-Input dictionary entry. Output:
///
/// ```text
/// sig1=("@method" "@target-uri" "@authority" "content-digest");\
///     created=1700000000;keyid="workspace-1";alg="ed25519"
/// ```
fn build_signature_input_header(
    label: &str,
    components: &[String],
    params: &SignatureInputParams,
) -> String {
    let mut out = String::new();
    out.push_str(label);
    out.push_str("=(");
    for (idx, c) in components.iter().enumerate() {
        if idx > 0 {
            out.push(' ');
        }
        out.push('"');
        out.push_str(&c.to_ascii_lowercase());
        out.push('"');
    }
    out.push(')');
    if let Some(created) = params.created {
        out.push_str(";created=");
        out.push_str(&created.to_string());
    }
    if let Some(expires) = params.expires {
        out.push_str(";expires=");
        out.push_str(&expires.to_string());
    }
    out.push_str(";keyid=\"");
    out.push_str(&params.keyid);
    out.push('"');
    out.push_str(";alg=\"");
    out.push_str(algorithm_wire_token(params.alg));
    out.push('"');
    if let Some(tag) = &params.tag {
        out.push_str(";tag=\"");
        out.push_str(tag);
        out.push('"');
    }
    out
}

// --- Tests ------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::signatures::{
        MessageSignatureConfig, MessageSignatureVerifier, SignatureAlgorithm, VerifyVerdict,
    };
    use ed25519_dalek::{SigningKey, SECRET_KEY_LENGTH};
    use rand::RngCore;

    fn fresh_ed25519_secret() -> [u8; SECRET_KEY_LENGTH] {
        let mut secret = [0u8; SECRET_KEY_LENGTH];
        rand::rngs::OsRng.fill_bytes(&mut secret);
        secret
    }

    fn signer_and_verifier_ed25519() -> (MessageSigner, MessageSignatureVerifier) {
        let secret = fresh_ed25519_secret();
        let signing_key = SigningKey::from_bytes(&secret);
        let verifying_key = signing_key.verifying_key();

        let signer = MessageSigner::new(SignerConfig {
            key_id: "workspace-1".to_string(),
            algorithm: SignatureAlgorithm::Ed25519,
            secret: secret.to_vec(),
            covered_components: Vec::new(),
        })
        .expect("signer");

        let verifier = MessageSignatureVerifier::new(MessageSignatureConfig {
            algorithm: SignatureAlgorithm::Ed25519,
            key_id: "workspace-1".to_string(),
            key: hex::encode(verifying_key.to_bytes()),
            required_components: Vec::new(),
            clock_skew_seconds: 30,
        })
        .expect("verifier");
        (signer, verifier)
    }

    fn signer_and_verifier_hmac() -> (MessageSigner, MessageSignatureVerifier) {
        let secret_hex = "00112233445566778899aabbccddeeff";
        let secret = hex::decode(secret_hex).unwrap();
        let signer = MessageSigner::new(SignerConfig {
            key_id: "workspace-1".to_string(),
            algorithm: SignatureAlgorithm::HmacSha256,
            secret: secret.clone(),
            covered_components: Vec::new(),
        })
        .expect("signer");
        let verifier = MessageSignatureVerifier::new(MessageSignatureConfig {
            algorithm: SignatureAlgorithm::HmacSha256,
            key_id: "workspace-1".to_string(),
            key: secret_hex.to_string(),
            required_components: Vec::new(),
            clock_skew_seconds: 30,
        })
        .expect("verifier");
        (signer, verifier)
    }

    fn sample_post_request() -> Request<Bytes> {
        Request::builder()
            .method("POST")
            .uri("https://api.example.com/v1/items?lang=en")
            .header("host", "api.example.com")
            .body(Bytes::from_static(b"{\"name\":\"widget\"}"))
            .unwrap()
    }

    fn sample_get_request() -> Request<Bytes> {
        Request::builder()
            .method("GET")
            .uri("https://api.example.com/v1/health")
            .header("host", "api.example.com")
            .body(Bytes::new())
            .unwrap()
    }

    // --- Round-trip: ed25519 ---

    #[test]
    fn round_trip_ed25519_signed_request_verifies() {
        let (signer, verifier) = signer_and_verifier_ed25519();
        let signed = signer.sign_request(sample_post_request()).expect("sign");

        // The signer must have stamped all three headers.
        assert!(signed.headers().contains_key("content-digest"));
        assert!(signed.headers().contains_key("signature-input"));
        assert!(signed.headers().contains_key("signature"));

        match verifier.verify_request(&signed) {
            VerifyVerdict::Ok { signature_label } => {
                assert_eq!(signature_label, DEFAULT_SIGNATURE_LABEL);
            }
            VerifyVerdict::Failed { reason } => panic!("expected ok, got: {reason}"),
        }
    }

    // --- Web Bot Auth profile: tag + expires ---

    #[test]
    fn web_bot_auth_profile_stamps_tag_and_expires_and_round_trips() {
        let secret = fresh_ed25519_secret();
        let signing_key = SigningKey::from_bytes(&secret);
        let verifying_key = signing_key.verifying_key();
        let signer = MessageSigner::new(SignerConfig {
            key_id: "wba-1".to_string(),
            algorithm: SignatureAlgorithm::Ed25519,
            secret: secret.to_vec(),
            covered_components: Vec::new(),
        })
        .expect("signer")
        .with_web_bot_auth_profile("web-bot-auth", 300);

        let signed = signer.sign_request(sample_post_request()).expect("sign");
        let sig_input = signed
            .headers()
            .get("signature-input")
            .unwrap()
            .to_str()
            .unwrap();
        assert!(
            sig_input.contains(";tag=\"web-bot-auth\""),
            "signature-input must carry the web-bot-auth tag: {sig_input}"
        );
        assert!(
            sig_input.contains(";expires="),
            "signature-input must carry an expires param: {sig_input}"
        );

        // The inbound verifier parses tag/expires; a fresh signature with
        // a 300s lifetime must round-trip cleanly.
        let verifier = MessageSignatureVerifier::new(MessageSignatureConfig {
            algorithm: SignatureAlgorithm::Ed25519,
            key_id: "wba-1".to_string(),
            key: hex::encode(verifying_key.to_bytes()),
            required_components: Vec::new(),
            clock_skew_seconds: 30,
        })
        .expect("verifier");
        match verifier.verify_request(&signed) {
            VerifyVerdict::Ok { .. } => {}
            VerifyVerdict::Failed { reason } => panic!("expected ok, got: {reason}"),
        }
    }

    // --- Round-trip: hmac-sha256 ---

    #[test]
    fn round_trip_hmac_sha256_signed_request_verifies() {
        let (signer, verifier) = signer_and_verifier_hmac();
        let signed = signer.sign_request(sample_post_request()).expect("sign");
        match verifier.verify_request(&signed) {
            VerifyVerdict::Ok { .. } => {}
            VerifyVerdict::Failed { reason } => panic!("expected ok, got: {reason}"),
        }
    }

    // --- Body change after signing breaks verification ---

    #[test]
    fn tampering_with_body_after_signing_breaks_verification() {
        let (signer, verifier) = signer_and_verifier_ed25519();
        let signed = signer.sign_request(sample_post_request()).expect("sign");

        // Replace the body on the wire but keep all three signature
        // headers. Because content-digest is part of the covered set
        // and binds the body, the verifier must reject this even
        // though Signature-Input/Signature are still present.
        let (parts, _body) = signed.into_parts();
        let tampered = Request::from_parts(parts, Bytes::from_static(b"{\"name\":\"sabotage\"}"));

        // The tampered request still carries the original
        // content-digest header (which now mismatches the new body),
        // so the digest verifier would catch it. But the signature
        // covers the original content-digest header too: changing the
        // body would force the caller to recompute content-digest,
        // which would invalidate the signature. We exercise that path
        // here by recomputing the digest header to match the new body
        // and confirming the signature still fails.
        let new_digest = compute_content_digest(Algorithm::Sha256, tampered.body().as_ref());
        let mut headers = tampered.headers().clone();
        headers.insert(
            "content-digest",
            HeaderValue::from_str(&new_digest).unwrap(),
        );
        let (mut parts, body) = tampered.into_parts();
        parts.headers = headers;
        let rebuilt = Request::from_parts(parts, body);

        match verifier.verify_request(&rebuilt) {
            VerifyVerdict::Ok { .. } => {
                panic!("verifier accepted a request with a tampered body")
            }
            VerifyVerdict::Failed { reason } => {
                assert!(
                    reason.contains("cryptographic"),
                    "expected cryptographic failure, got: {reason}"
                );
            }
        }
    }

    // --- created timestamp freshness ---

    #[test]
    fn created_parameter_is_recent() {
        let (signer, _verifier) = signer_and_verifier_ed25519();
        let before = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs() as i64;
        let signed = signer.sign_request(sample_post_request()).expect("sign");
        let after = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs() as i64;

        let header = signed
            .headers()
            .get("signature-input")
            .expect("signature-input present")
            .to_str()
            .unwrap();
        let parsed = parse_signature_input(header).expect("parse");
        let entry = &parsed[0].1;
        let created = entry.params.created.expect("created present");
        // Within +/- 10s of "now". The bounds are inclusive because the
        // signer reads its own `now` between `before` and `after`.
        assert!(
            created >= before - 10,
            "created {created} < before {before}"
        );
        assert!(created <= after + 10, "created {created} > after {after}");
    }

    // --- Bodyless requests ---

    #[test]
    fn bodyless_request_signs_without_content_digest() {
        // A GET with no body should sign cleanly: the signer must drop
        // content-digest from the covered set rather than fail.
        let (signer, verifier) = signer_and_verifier_ed25519();
        let signed = signer.sign_request(sample_get_request()).expect("sign");

        assert!(
            !signed.headers().contains_key("content-digest"),
            "bodyless request should not carry content-digest"
        );

        let sig_input = signed
            .headers()
            .get("signature-input")
            .unwrap()
            .to_str()
            .unwrap();
        assert!(
            !sig_input.contains("\"content-digest\""),
            "covered set should not list content-digest for bodyless requests, got: {sig_input}"
        );

        match verifier.verify_request(&signed) {
            VerifyVerdict::Ok { .. } => {}
            VerifyVerdict::Failed { reason } => panic!("expected ok, got: {reason}"),
        }
    }

    // --- Pre-computed content-digest is preserved ---

    #[test]
    fn signer_preserves_caller_supplied_content_digest() {
        let (signer, _verifier) = signer_and_verifier_ed25519();
        // A caller (perhaps a streaming pipeline that used DigestSink
        // chunk by chunk) computed content-digest itself. The signer
        // must not overwrite it.
        let pre_existing = compute_content_digest(Algorithm::Sha256, b"{\"name\":\"widget\"}");
        let req = Request::builder()
            .method("POST")
            .uri("https://api.example.com/v1/items")
            .header("host", "api.example.com")
            .header("content-digest", &pre_existing)
            .body(Bytes::from_static(b"{\"name\":\"widget\"}"))
            .unwrap();
        let signed = signer.sign_request(req).expect("sign");
        assert_eq!(
            signed
                .headers()
                .get("content-digest")
                .unwrap()
                .to_str()
                .unwrap(),
            pre_existing
        );
    }

    // --- Custom covered components ---

    #[test]
    fn custom_covered_components_are_honoured() {
        let (_, _) = signer_and_verifier_hmac();
        let secret_hex = "00112233445566778899aabbccddeeff";
        let secret = hex::decode(secret_hex).unwrap();
        let signer = MessageSigner::new(SignerConfig {
            key_id: "workspace-1".to_string(),
            algorithm: SignatureAlgorithm::HmacSha256,
            secret,
            covered_components: vec!["@method".to_string(), "@path".to_string()],
        })
        .unwrap();
        let signed = signer.sign_request(sample_post_request()).expect("sign");
        let sig_input = signed
            .headers()
            .get("signature-input")
            .unwrap()
            .to_str()
            .unwrap();
        assert!(sig_input.contains("\"@method\""));
        assert!(sig_input.contains("\"@path\""));
        assert!(!sig_input.contains("\"content-digest\""));
        // The verifier still accepts it because none of these
        // components were tampered.
        let verifier = MessageSignatureVerifier::new(MessageSignatureConfig {
            algorithm: SignatureAlgorithm::HmacSha256,
            key_id: "workspace-1".to_string(),
            key: secret_hex.to_string(),
            required_components: Vec::new(),
            clock_skew_seconds: 30,
        })
        .unwrap();
        match verifier.verify_request(&signed) {
            VerifyVerdict::Ok { .. } => {}
            VerifyVerdict::Failed { reason } => panic!("expected ok, got: {reason}"),
        }
    }

    // --- Key-shape validation ---

    #[test]
    fn ed25519_secret_must_be_32_bytes() {
        let err = MessageSigner::new(SignerConfig {
            key_id: "k".to_string(),
            algorithm: SignatureAlgorithm::Ed25519,
            secret: vec![0u8; 8],
            covered_components: Vec::new(),
        })
        .unwrap_err();
        assert!(
            matches!(err, SignerError::InvalidKey(ref m) if m.contains("32 bytes")),
            "got {err:?}"
        );
    }

    #[test]
    fn hmac_secret_must_be_non_empty() {
        let err = MessageSigner::new(SignerConfig {
            key_id: "k".to_string(),
            algorithm: SignatureAlgorithm::HmacSha256,
            secret: Vec::new(),
            covered_components: Vec::new(),
        })
        .unwrap_err();
        assert!(
            matches!(err, SignerError::InvalidKey(ref m) if m.contains("non-empty")),
            "got {err:?}"
        );
    }

    #[test]
    fn debug_does_not_leak_secret() {
        let signer = MessageSigner::new(SignerConfig {
            key_id: "workspace-1".to_string(),
            algorithm: SignatureAlgorithm::HmacSha256,
            secret: b"super-secret".to_vec(),
            covered_components: Vec::new(),
        })
        .unwrap();
        let debug_str = format!("{signer:?}");
        assert!(
            !debug_str.contains("super-secret"),
            "debug output leaked secret: {debug_str}"
        );
    }
}
