package routing

import (
	"testing"

	"github.com/soapbucket/sbproxy/internal/ai"
)

func makeTestRegistry() *ai.ProviderRegistry {
	return &ai.ProviderRegistry{
		Providers: map[string]ai.ProviderDef{
			"openai": {
				DisplayName: "OpenAI",
				Models: map[string]ai.ModelDef{
					"gpt-4": {ContextWindow: 8192},
					"gpt-4-turbo": {ContextWindow: 128000},
					"gpt-4o": {ContextWindow: 128000},
					"gpt-3.5-turbo": {ContextWindow: 16384},
				},
			},
			"anthropic": {
				DisplayName: "Anthropic",
				Models: map[string]ai.ModelDef{
					"claude-sonnet": {ContextWindow: 200000},
					"claude-opus":   {ContextWindow: 200000},
					"claude-haiku":  {ContextWindow: 200000},
				},
			},
		},
	}
}

func TestFallbackContextConfigured(t *testing.T) {
	reg := makeTestRegistry()
	configured := map[string]string{
		"gpt-4": "gpt-4-turbo",
	}
	fm := NewContextFallbackMap(configured, reg)

	// Configured fallback should be returned when the target fits.
	model, ok := fm.FindLarger("gpt-4", 50000)
	if !ok {
		t.Fatal("expected configured fallback to be found")
	}
	if model != "gpt-4-turbo" {
		t.Fatalf("expected gpt-4-turbo, got %s", model)
	}
}

func TestFallbackContextConfiguredTooSmall(t *testing.T) {
	reg := makeTestRegistry()
	configured := map[string]string{
		"gpt-4": "gpt-3.5-turbo", // 16k window - too small for 50k requirement
	}
	fm := NewContextFallbackMap(configured, reg)

	// Configured fallback is too small, should fall through to auto-generation.
	model, ok := fm.FindLarger("gpt-4", 50000)
	if !ok {
		t.Fatal("expected auto-generated fallback")
	}
	// Should pick gpt-4-turbo or gpt-4o (128k), whichever sorts first.
	if model != "gpt-4-turbo" && model != "gpt-4o" {
		t.Fatalf("expected gpt-4-turbo or gpt-4o, got %s", model)
	}
}

func TestFallbackContextAutoGenerated(t *testing.T) {
	reg := makeTestRegistry()
	fm := NewContextFallbackMap(nil, reg)

	// gpt-4 (8k) should fall back to a larger model from the same provider.
	model, ok := fm.FindLarger("gpt-4", 20000)
	if !ok {
		t.Fatal("expected auto-generated fallback to be found")
	}
	// gpt-3.5-turbo is 16k (too small), so it should pick gpt-4-turbo or gpt-4o (128k).
	if model != "gpt-4-turbo" && model != "gpt-4o" {
		t.Fatalf("expected gpt-4-turbo or gpt-4o, got %s", model)
	}
}

func TestFallbackContextPicksSmallestSufficient(t *testing.T) {
	// Custom registry where there's a clear smallest-sufficient choice.
	reg := &ai.ProviderRegistry{
		Providers: map[string]ai.ProviderDef{
			"test": {
				Models: map[string]ai.ModelDef{
					"small":  {ContextWindow: 4096},
					"medium": {ContextWindow: 16384},
					"large":  {ContextWindow: 128000},
				},
			},
		},
	}
	fm := NewContextFallbackMap(nil, reg)

	model, ok := fm.FindLarger("small", 10000)
	if !ok {
		t.Fatal("expected fallback")
	}
	if model != "medium" {
		t.Fatalf("expected medium (smallest sufficient), got %s", model)
	}
}

func TestFallbackContextNoFallbackAvailable(t *testing.T) {
	reg := makeTestRegistry()
	fm := NewContextFallbackMap(nil, reg)

	// gpt-4-turbo already has the largest window (128k). Requesting more than that
	// should return no fallback.
	_, ok := fm.FindLarger("gpt-4-turbo", 200000)
	if ok {
		t.Fatal("expected no fallback for the largest model in provider")
	}
}

func TestFallbackContextUnknownModel(t *testing.T) {
	reg := makeTestRegistry()
	fm := NewContextFallbackMap(nil, reg)

	_, ok := fm.FindLarger("nonexistent-model", 10000)
	if ok {
		t.Fatal("expected no fallback for unknown model")
	}
}

func TestFallbackContextNilRegistry(t *testing.T) {
	configured := map[string]string{
		"gpt-4": "gpt-4-turbo",
	}
	fm := NewContextFallbackMap(configured, nil)

	// With no registry, configured fallback is trusted without verification.
	model, ok := fm.FindLarger("gpt-4", 50000)
	if !ok {
		t.Fatal("expected configured fallback with nil registry")
	}
	if model != "gpt-4-turbo" {
		t.Fatalf("expected gpt-4-turbo, got %s", model)
	}

	// Auto-generation should not work without a registry.
	_, ok = fm.FindLarger("gpt-3.5-turbo", 50000)
	if ok {
		t.Fatal("expected no auto-generated fallback with nil registry")
	}
}

func TestFallbackContextCrossProviderNotAllowed(t *testing.T) {
	reg := makeTestRegistry()
	fm := NewContextFallbackMap(nil, reg)

	// claude-haiku (200k) already has a huge window. Even though OpenAI models exist,
	// auto-generation only considers models from the same provider.
	// Request something larger than anthropic's 200k - should fail.
	_, ok := fm.FindLarger("claude-haiku", 300000)
	if ok {
		t.Fatal("expected no cross-provider fallback")
	}
}
