//! `/licenses.xml` projection per the RSL Collective spec at
//! <https://rslstandard.org/rsl>.
//!
//! Document shape: a single `<rsl>` root in the canonical
//! `https://rslstandard.org/rsl` namespace, with one `<content>`
//! element per licensed scope. Each `<content>` carries a `url`
//! attribute identifying the route (or hostname-wide globs) the
//! enclosed `<license>` body applies to. Wave 4 emits a single
//! origin-wide entry; the `<content url>` is set to the wildcard
//! `https://<hostname>/*`, matching the spec's globbing convention
//! for "every URL on this origin". Per-route licensing is a future
//! extension and is not generated by this projection today.
//!
//! The URN is `urn:rsl:1.0:<origin_hostname>:<config_version_hash>`
//! and is carried as a `urn` attribute on the inner `<license>`
//! element.
//!
//! Mapping table (origin-level `Content-Signal` to `<ai-use>`):
//!
//! | `Content-Signal` value | RSL `<ai-use>` assertion |
//! |---|---|
//! | `ai-train` | `<ai-use type="training" licensed="true" />` |
//! | `ai-input` | `<ai-use type="inference" licensed="true" />` |
//! | `search` | `<ai-use type="search-index" licensed="true" />` |
//! | absent | `<ai-use type="training" licensed="false" />` |
//!
//! ## Internal contract: `RequestContext.rsl_urn`
//!
//! The data-plane handler that serves this projection stamps the URN
//! returned by `render` onto `RequestContext.rsl_urn` so the Wave 4
//! JSON envelope (rust-A's G4.4) can read it for the `license` field
//! without re-parsing the projection body. Any caller that wants to
//! emit an RSL-aware response on the same hostname should consult
//! `current_projections().rsl_urns` for the URN; the URN equals
//! `urn:rsl:1.0:<hostname>:<config_version>` so it is also derivable
//! without the cache when needed.

/// Render `(licenses_xml, urn)` for a single origin.
///
/// `content_signal` is the parsed value of the origin's
/// `extensions["content_signal"]` slot (None when absent). Returns the
/// canonical RSL document (per <https://rslstandard.org/rsl>) and the
/// URN that identifies the inner license element; the URN is the same
/// value the response middleware stamps on `RequestContext.rsl_urn`.
pub fn render(
    hostname: &str,
    content_signal: Option<&str>,
    config_version: u64,
) -> (String, String) {
    let urn = format!("urn:rsl:1.0:{hostname}:{config_version}");

    // RSL mapping. Absent signal asserts default-deny (training,
    // licensed="false").
    let (ai_type, licensed) = match content_signal {
        Some("ai-train") => ("training", "true"),
        Some("ai-input") => ("inference", "true"),
        Some("search") => ("search-index", "true"),
        _ => ("training", "false"),
    };

    // The `<content url>` value is the canonical "every URL on this
    // origin" glob per the RSL Collective spec prose. Wave 4 has a
    // single origin-wide license per origin, so we emit one
    // `<content>` element scoped to `https://<hostname>/*`. Per-route
    // grouping (one `<content>` per route) is an open extension and
    // would split this loop along `tier.route_pattern` once Wave 5
    // wires per-tier licensing.
    let content_url = format!("https://{hostname}/*");

    // Quick-xml is not pulled into sbproxy-modules directly: the
    // document shape is small enough that hand-rolled emission with
    // strict escaping is cleaner than wiring a writer for one
    // element. The escape helper handles the five XML predefined
    // entities; URNs and hostnames pass through unchanged because RSL
    // restricts them to URI-safe characters.
    let mut xml = String::with_capacity(512);
    xml.push_str(r#"<?xml version="1.0" encoding="UTF-8"?>"#);
    xml.push('\n');
    xml.push_str(r#"<rsl xmlns="https://rslstandard.org/rsl" version="1.0">"#);
    xml.push('\n');
    xml.push_str(&format!(
        "  <content url=\"{}\">\n",
        escape_xml_attr(&content_url)
    ));
    xml.push_str(&format!(
        "    <license urn=\"{}\">\n",
        escape_xml_attr(&urn)
    ));
    xml.push_str(&format!(
        "      <origin hostname=\"{}\" />\n",
        escape_xml_attr(hostname)
    ));
    xml.push_str(&format!(
        "      <ai-use type=\"{ai_type}\" licensed=\"{licensed}\" />\n"
    ));
    if let Some(signal) = content_signal {
        xml.push_str(&format!(
            "      <content-signal>{}</content-signal>\n",
            escape_xml_text(signal)
        ));
    }
    xml.push_str("    </license>\n");
    xml.push_str("  </content>\n");
    xml.push_str("</rsl>\n");

    (xml, urn)
}

fn escape_xml_text(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            _ => out.push(c),
        }
    }
    out
}

fn escape_xml_attr(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn urn_format_matches_spec() {
        let (_xml, urn) = render("shop.example.com", Some("ai-train"), 42);
        assert_eq!(urn, "urn:rsl:1.0:shop.example.com:42");
    }

    #[test]
    fn ai_train_maps_to_training_licensed_true() {
        let (xml, _) = render("h", Some("ai-train"), 1);
        assert!(xml.contains(r#"<ai-use type="training" licensed="true" />"#));
        assert!(xml.contains("<content-signal>ai-train</content-signal>"));
    }

    #[test]
    fn ai_input_maps_to_inference_licensed_true() {
        let (xml, _) = render("h", Some("ai-input"), 1);
        assert!(xml.contains(r#"<ai-use type="inference" licensed="true" />"#));
    }

    #[test]
    fn search_maps_to_search_index_licensed_true() {
        let (xml, _) = render("h", Some("search"), 1);
        assert!(xml.contains(r#"<ai-use type="search-index" licensed="true" />"#));
    }

    #[test]
    fn absent_signal_maps_to_default_deny() {
        let (xml, _) = render("h", None, 1);
        assert!(xml.contains(r#"<ai-use type="training" licensed="false" />"#));
        // No content-signal element when the signal is absent.
        assert!(!xml.contains("<content-signal>"));
    }

    #[test]
    fn unknown_signal_falls_back_to_default_deny() {
        let (xml, _) = render("h", Some("custom-future-value"), 1);
        // Falls into the catch-all branch (default-deny).
        assert!(xml.contains(r#"<ai-use type="training" licensed="false" />"#));
        // We still echo the signal text (escaped) for forensics so
        // the operator can see what value reached the projection.
        assert!(xml.contains("<content-signal>custom-future-value</content-signal>"));
    }

    #[test]
    fn xml_namespace_is_canonical_rsl_collective() {
        let (xml, _) = render("h", Some("ai-train"), 1);
        assert!(xml.starts_with(r#"<?xml version="1.0" encoding="UTF-8"?>"#));
        assert!(
            xml.contains(r#"<rsl xmlns="https://rslstandard.org/rsl" version="1.0">"#),
            "namespace must be the canonical RSL Collective URI; got:\n{xml}"
        );
        // Make sure the legacy non-canonical namespace is gone.
        assert!(
            !xml.contains("rsl.ai/spec/1.0"),
            "legacy rsl.ai/spec/1.0 namespace must not appear"
        );
    }

    #[test]
    fn document_nests_license_under_content_with_url_attr() {
        let (xml, _) = render("shop.example.com", Some("ai-train"), 1);
        // The license body must live under a `<content url=...>`
        // element, not be a sibling of `<rsl>`.
        assert!(
            xml.contains(r#"<content url="https://shop.example.com/*">"#),
            "<content> element must wrap the license with a url attr; got:\n{xml}"
        );
        assert!(xml.contains("<license urn="));
        // Order: <rsl> -> <content> -> <license>.
        let rsl_idx = xml.find("<rsl ").expect("<rsl> present");
        let content_idx = xml.find("<content ").expect("<content> present");
        let license_idx = xml.find("<license ").expect("<license> present");
        assert!(
            rsl_idx < content_idx && content_idx < license_idx,
            "ordering must be <rsl> -> <content> -> <license>"
        );
        // Closing tags balance.
        assert!(xml.contains("</license>"));
        assert!(xml.contains("</content>"));
        assert!(xml.contains("</rsl>"));
    }

    #[test]
    fn hostname_with_special_chars_is_escaped_in_attr() {
        // Constructed (not realistic) hostname to verify the attribute
        // escaper is wired even though DNS hostnames cannot legally
        // contain `&`.
        let (xml, _) = render("a&b", Some("ai-train"), 1);
        assert!(xml.contains("hostname=\"a&amp;b\""));
        // The url attribute must also be escaped.
        assert!(xml.contains("url=\"https://a&amp;b/*\""));
    }

    #[test]
    fn deterministic_output() {
        let (a, _) = render("h", Some("ai-train"), 1);
        let (b, _) = render("h", Some("ai-train"), 1);
        assert_eq!(a, b);
    }
}
