//! `/licenses.xml` projection per the RSL Collective spec at
//! <https://rslstandard.org/rsl>.
//!
//! Document shape: a single `<rsl>` root in the canonical
//! `https://rslstandard.org/rsl` namespace, with one `<content>`
//! element per licensed scope. Each `<content>` carries a `url`
//! attribute identifying the route (or hostname-wide globs) the
//! enclosed `<license>` body applies to. Wave 4 emits a single
//! origin-wide entry; the `<content url>` is set to the wildcard
//! `https://<hostname>/*`, matching the spec's globbing convention
//! for "every URL on this origin". Per-route licensing is a future
//! extension and is not generated by this projection today.
//!
//! The URN is `urn:rsl:1.0:<origin_hostname>:<config_version_hash>`
//! and is carried as a `urn` attribute on the inner `<license>`
//! element.
//!
//! Mapping table (origin-level `Content-Signal` to normative RSL 1.0
//! tokens; see WOR-944). The token vocabulary comes from RSL §3.4.1
//! and goes inside `<permits type="usage">` / `<prohibits type="usage">`
//! per §3.5 + the §4.8 example. The earlier `<ai-use>` element this
//! module emitted was NOT a normative RSL 1.0 element; it has been
//! replaced with `<permits>` / `<prohibits>`.
//!
//! | `Content-Signal` value | RSL element |
//! |---|---|
//! | `ai-train` | `<permits type="usage">ai-train</permits>` |
//! | `ai-input` | `<permits type="usage">ai-input</permits>` |
//! | `search` | `<permits type="usage">search</permits>` |
//! | absent | (no `<permits>` or `<prohibits>` element; silent-permissive per spec) |
//!
//! The structured `ContentSignals` set (search / ai_input / ai_train
//! each `Some(true)` / `Some(false)` / `None`) splits the same
//! vocabulary across `<permits>` and `<prohibits>` per the
//! "prohibits wins" MUST conflict rule (§3.1.1, §3.6). The operator
//! can also declare a `rsl_vocab:` block with user (commercial /
//! non-commercial / education / government / personal per §3.4.1.2)
//! and geo (ISO 3166-1 alpha-2) tiers.
//!
//! ## Internal contract: `RequestContext.rsl_urn`
//!
//! The data-plane handler that serves this projection stamps the URN
//! returned by `render` onto `RequestContext.rsl_urn` so the Wave 4
//! JSON envelope (rust-A's G4.4) can read it for the `license` field
//! without re-parsing the projection body. Any caller that wants to
//! emit an RSL-aware response on the same hostname should consult
//! `current_projections().rsl_urns` for the URN; the URN equals
//! `urn:rsl:1.0:<hostname>:<config_version>` so it is also derivable
//! without the cache when needed.

use crate::policy::ai_crawl::ContentSignals;

/// WOR-944 tier-1 vocab tokens declared by the operator on
/// `ai_crawl_control.rsl_vocab.{user,geo}`. `permit` and `prohibit`
/// are each rendered as a single `<permits type="<kind>">` /
/// `<prohibits type="<kind>">` element with the tokens
/// space-separated per RSL 1.0 §3.5 and the §4.8 example. An empty
/// list emits no element; both empty means the tier is silent for
/// that origin.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct TokenTier {
    /// Tokens placed inside the corresponding `<permits>` element.
    pub permit: Vec<String>,
    /// Tokens placed inside the corresponding `<prohibits>` element.
    pub prohibit: Vec<String>,
}

impl TokenTier {
    /// True when both lists are empty (the tier is silent).
    fn is_silent(&self) -> bool {
        self.permit.is_empty() && self.prohibit.is_empty()
    }
}

/// WOR-944 RSL tier-1 vocab the operator declares on
/// `ai_crawl_control.rsl_vocab`. `user` carries the RSL §3.4.1.2
/// audience vocabulary (commercial, non-commercial, education,
/// government, personal); `geo` carries ISO 3166-1 alpha-2 country
/// codes. The usage tier (`ai-train`, `ai-input`, `search`) is still
/// driven from the existing `content_signals` block so the two
/// stay consistent.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct RslVocab {
    /// Tier-1 user/audience tokens.
    pub user: TokenTier,
    /// Tier-1 geo tokens (ISO 3166-1 alpha-2).
    pub geo: TokenTier,
}

/// Render one `<permits>` / `<prohibits>` pair for a given
/// `type=<kind>` value. Emits nothing when both lists are empty.
fn render_tier_pair(kind: &str, tier: &TokenTier) -> String {
    let mut s = String::new();
    if !tier.permit.is_empty() {
        s.push_str(&format!(
            "      <permits type=\"{}\">{}</permits>\n",
            escape_xml_attr(kind),
            escape_xml_text(&tier.permit.join(" "))
        ));
    }
    if !tier.prohibit.is_empty() {
        s.push_str(&format!(
            "      <prohibits type=\"{}\">{}</prohibits>\n",
            escape_xml_attr(kind),
            escape_xml_text(&tier.prohibit.join(" "))
        ));
    }
    s
}

/// Render the usage tier from a [`ContentSignals`] set. Each signal
/// becomes a token inside the corresponding `<permits>` /
/// `<prohibits>` element. Absent signals are omitted (silent-permissive
/// per RSL spec); a `Some(false)` is a `<prohibits>` per the "prohibits
/// wins" MUST conflict rule in §3.1.1/§3.6.
fn render_usage_tier(signals: &ContentSignals) -> String {
    let mut tier = TokenTier::default();
    // Fixed order matches the legacy `<ai-use>` emission order so
    // dashboards / tests that grep the body in a stable order keep
    // working (search, inference, training -> RSL tokens
    // search, ai-input, ai-train).
    for (value, token) in [
        (signals.search, "search"),
        (signals.ai_input, "ai-input"),
        (signals.ai_train, "ai-train"),
    ] {
        match value {
            Some(true) => tier.permit.push(token.to_string()),
            Some(false) => tier.prohibit.push(token.to_string()),
            None => {}
        }
    }
    render_tier_pair("usage", &tier)
}

/// RSL 1.0 `<payment>` terms for a license element.
///
/// `payment_type` is an RSL 1.0 payment-enum value (`free`, `crawl`,
/// `purchase`, `subscription`, `training`, `use`, `attribution`).
/// `amount` + `currency` are emitted for priced types and omitted for
/// `free`. SBproxy derives these from the `ai_crawl_control` policy: a
/// per-crawl price maps to `type="crawl"` with the configured price /
/// currency; an unpriced origin maps to `type="free"`.
///
/// `standard` (WOR-944) is the optional `<standard>` child element
/// that points at the reuse framework for an attribution payment
/// (typically `https://creativecommons.org/licenses/by/4.0/` or
/// similar). Omitted when unset; when set, the `<payment>` element
/// renders as a container with a `<standard>` child rather than as
/// the self-closing form.
#[derive(Debug, Clone, PartialEq)]
pub struct PaymentTerms {
    /// RSL payment-enum value.
    pub payment_type: String,
    /// Price amount for a priced type; `None` for `free`.
    pub amount: Option<f64>,
    /// Currency code for a priced type; `None` for `free`.
    pub currency: Option<String>,
    /// Optional `<standard>` URL — the reuse framework an
    /// attribution payment points to (CC-BY, etc.). Per RSL 1.0
    /// schema, the `<standard>` child sits inside `<payment>`.
    pub standard: Option<String>,
}

impl PaymentTerms {
    /// Free content: `<payment type="free" />`.
    pub fn free() -> Self {
        Self {
            payment_type: "free".to_string(),
            amount: None,
            currency: None,
            standard: None,
        }
    }

    /// Emit the `<payment ... />` element (indented for the `<license>`
    /// body). Returns the empty string for an unset type so callers can
    /// unconditionally concatenate. When `standard` is set, emits the
    /// container form with a `<standard>` child; otherwise emits the
    /// self-closing form (backwards-compatible with PR #318).
    fn to_xml(&self) -> String {
        if self.payment_type.is_empty() {
            return String::new();
        }
        let mut s = format!(
            "      <payment type=\"{}\"",
            escape_xml_attr(&self.payment_type)
        );
        if let Some(amount) = self.amount {
            s.push_str(&format!(" amount=\"{amount}\""));
        }
        if let Some(currency) = &self.currency {
            s.push_str(&format!(" currency=\"{}\"", escape_xml_attr(currency)));
        }
        if let Some(standard) = &self.standard {
            s.push_str(">\n");
            s.push_str(&format!(
                "        <standard>{}</standard>\n",
                escape_xml_text(standard)
            ));
            s.push_str("      </payment>\n");
        } else {
            s.push_str(" />\n");
        }
        s
    }
}

/// Render `(licenses_xml, urn)` for a single origin.
///
/// `content_signal` is the parsed value of the origin's
/// `extensions["content_signal"]` slot (None when absent). `payment`
/// declares the RSL `<payment>` terms (None omits the element). Returns
/// the canonical RSL document (per <https://rslstandard.org/rsl>) and
/// the URN that identifies the inner license element; the URN is the
/// same value the response middleware stamps on
/// `RequestContext.rsl_urn`.
pub fn render(
    hostname: &str,
    content_signal: Option<&str>,
    payment: Option<&PaymentTerms>,
    config_version: u64,
) -> (String, String) {
    let urn = format!("urn:rsl:1.0:{hostname}:{config_version}");

    // WOR-944: legacy single-value mapping into RSL 1.0 tokens.
    // Absent signal is silent-permissive per spec; the old code
    // synthesised `<ai-use licensed="false">` which is non-conformant
    // (RSL 1.0 has no `<ai-use>` element at all).
    let mut usage = TokenTier::default();
    match content_signal {
        Some("ai-train") => usage.permit.push("ai-train".to_string()),
        Some("ai-input") => usage.permit.push("ai-input".to_string()),
        Some("search") => usage.permit.push("search".to_string()),
        _ => {}
    }

    // The `<content url>` value is the canonical "every URL on this
    // origin" glob per the RSL Collective spec prose. Wave 4 has a
    // single origin-wide license per origin, so we emit one
    // `<content>` element scoped to `https://<hostname>/*`. Per-route
    // grouping (one `<content>` per route) is an open extension.
    let content_url = format!("https://{hostname}/*");

    // Quick-xml is not pulled into sbproxy-modules directly: the
    // document shape is small enough that hand-rolled emission with
    // strict escaping is cleaner than wiring a writer for one
    // element. The escape helper handles the five XML predefined
    // entities; URNs and hostnames pass through unchanged because RSL
    // restricts them to URI-safe characters.
    let mut xml = String::with_capacity(512);
    xml.push_str(r#"<?xml version="1.0" encoding="UTF-8"?>"#);
    xml.push('\n');
    xml.push_str(r#"<rsl xmlns="https://rslstandard.org/rsl" version="1.0">"#);
    xml.push('\n');
    xml.push_str(&format!(
        "  <content url=\"{}\">\n",
        escape_xml_attr(&content_url)
    ));
    xml.push_str(&format!(
        "    <license urn=\"{}\">\n",
        escape_xml_attr(&urn)
    ));
    xml.push_str(&format!(
        "      <origin hostname=\"{}\" />\n",
        escape_xml_attr(hostname)
    ));
    if let Some(payment) = payment {
        xml.push_str(&payment.to_xml());
    }
    xml.push_str(&render_tier_pair("usage", &usage));
    // Sbproxy-extension `<content-signal>` for the forensic trail.
    // Spec-aware consumers ignore unknown elements; the audit hook
    // wants this echo because it ties the projection back to the
    // operator's declared signal verbatim.
    if let Some(signal) = content_signal {
        xml.push_str(&format!(
            "      <content-signal>{}</content-signal>\n",
            escape_xml_text(signal)
        ));
    }
    xml.push_str("    </license>\n");
    xml.push_str("  </content>\n");
    xml.push_str("</rsl>\n");

    (xml, urn)
}

/// WOR-808: one license tier declared by the operator. The TollBit
/// model splits the same origin into multiple priced offerings
/// (summarize vs full-display, for example) so a marketplace can buy
/// the cheap tier for snippet generation and the expensive tier for
/// full-page reuse. Each tier renders as its own `<license>` element
/// under the shared `<content>`, with `urn` carrying a fragment that
/// disambiguates the tier (`urn:rsl:1.0:<host>:<version>#<name>`).
#[derive(Debug, Clone, PartialEq)]
pub struct LicenseTier {
    /// Tier name (e.g. `summarize`, `full-display`). Becomes the URN
    /// fragment and is preserved verbatim in the rendered URN.
    pub name: String,
    /// Payment terms for this tier. Each tier carries its own price
    /// so the cheap tier and expensive tier render independently.
    pub payment: PaymentTerms,
    /// Per-tier usage signals: what the tier permits and prohibits.
    /// Splits the same way `ContentSignals` does (Some(true) = permit,
    /// Some(false) = prohibit, None = absent / silent-permissive).
    pub signals: ContentSignals,
}

/// Render `(licenses_xml, primary_urn)` for an origin that declares
/// two or more license tiers.
///
/// One `<license>` element is emitted per tier, all inside a single
/// `<content url="https://<host>/*">` element. Each `<license>` gets
/// the urn `urn:rsl:1.0:<host>:<version>#<tier-name>`. The returned
/// `primary_urn` is the un-fragmented form
/// (`urn:rsl:1.0:<host>:<version>`) so the pipeline's
/// `rsl_urn` stamping path keeps working unchanged; consumers that
/// need a specific tier URN read the per-tier fragment off the XML.
///
/// `vocab` slots its `user` / `geo` `<permits>`/`<prohibits>` pairs
/// into every tier's `<license>` body (the user / geo tier vocab is
/// origin-wide, not per-tier). An empty `tiers` slice falls back to
/// emitting a single placeholder license; callers should use
/// [`render_signals_with_vocab`] when no tiers are declared.
pub fn render_tiered(
    hostname: &str,
    tiers: &[LicenseTier],
    vocab: &RslVocab,
    config_version: u64,
) -> (String, String) {
    let primary_urn = format!("urn:rsl:1.0:{hostname}:{config_version}");
    let content_url = format!("https://{hostname}/*");

    let mut xml = String::with_capacity(1024);
    xml.push_str(r#"<?xml version="1.0" encoding="UTF-8"?>"#);
    xml.push('\n');
    xml.push_str(r#"<rsl xmlns="https://rslstandard.org/rsl" version="1.0">"#);
    xml.push('\n');
    xml.push_str(&format!(
        "  <content url=\"{}\">\n",
        escape_xml_attr(&content_url)
    ));
    for tier in tiers {
        let tier_urn = format!("{primary_urn}#{}", tier.name);
        xml.push_str(&format!(
            "    <license urn=\"{}\">\n",
            escape_xml_attr(&tier_urn)
        ));
        xml.push_str(&format!(
            "      <origin hostname=\"{}\" />\n",
            escape_xml_attr(hostname)
        ));
        xml.push_str(&tier.payment.to_xml());
        xml.push_str(&render_usage_tier(&tier.signals));
        if !vocab.user.is_silent() {
            xml.push_str(&render_tier_pair("user", &vocab.user));
        }
        if !vocab.geo.is_silent() {
            xml.push_str(&render_tier_pair("geo", &vocab.geo));
        }
        if let Some(directive) = tier.signals.directive_value() {
            xml.push_str(&format!(
                "      <content-signal>{}</content-signal>\n",
                escape_xml_text(&directive)
            ));
        }
        xml.push_str("    </license>\n");
    }
    xml.push_str("  </content>\n");
    xml.push_str("</rsl>\n");

    (xml, primary_urn)
}

/// Render `(licenses_xml, urn)` from a structured [`ContentSignals`]
/// set (WOR-804).
///
/// This is the multi-signal sibling of [`render`]. When the operator
/// declares Content Signals on the `ai_crawl_control` policy, the same
/// set drives both the `robots.txt` `Content-Signal:` directive and
/// the RSL document, so the two can never contradict. One `<ai-use>`
/// element is emitted per declared signal:
///
/// | signal | RSL `<ai-use type=...>` |
/// |---|---|
/// | `search` | `search-index` |
/// | `ai_input` | `inference` |
/// | `ai_train` | `training` |
///
/// `licensed` is `"true"` for a `=yes` signal and `"false"` for a
/// `=no` signal. The raw directive value (e.g. `search=yes,
/// ai-train=no`) is echoed in a `<content-signal>` element for
/// forensics. Callers use [`render`] (the single-value legacy path)
/// when no structured signals are configured.
pub fn render_signals(
    hostname: &str,
    signals: &ContentSignals,
    payment: Option<&PaymentTerms>,
    config_version: u64,
) -> (String, String) {
    render_signals_with_vocab(
        hostname,
        signals,
        payment,
        &RslVocab::default(),
        config_version,
    )
}

/// WOR-944: full sibling of [`render_signals`] that also emits the
/// operator-declared tier-1 user / geo vocab. `vocab` is read from
/// the `ai_crawl_control.rsl_vocab` config block; the default (no
/// vocab declared) renders the same document `render_signals` does.
///
/// Element order inside `<license>`:
/// `<origin>`, `<payment>`, `<permits type="usage">` /
/// `<prohibits type="usage">` (from `signals`),
/// `<permits type="user">` / `<prohibits type="user">` (from
/// `vocab.user`), `<permits type="geo">` / `<prohibits type="geo">`
/// (from `vocab.geo`), then the sbproxy-extension
/// `<content-signal>` echo for the audit trail.
pub fn render_signals_with_vocab(
    hostname: &str,
    signals: &ContentSignals,
    payment: Option<&PaymentTerms>,
    vocab: &RslVocab,
    config_version: u64,
) -> (String, String) {
    let urn = format!("urn:rsl:1.0:{hostname}:{config_version}");
    let content_url = format!("https://{hostname}/*");

    let mut xml = String::with_capacity(512);
    xml.push_str(r#"<?xml version="1.0" encoding="UTF-8"?>"#);
    xml.push('\n');
    xml.push_str(r#"<rsl xmlns="https://rslstandard.org/rsl" version="1.0">"#);
    xml.push('\n');
    xml.push_str(&format!(
        "  <content url=\"{}\">\n",
        escape_xml_attr(&content_url)
    ));
    xml.push_str(&format!(
        "    <license urn=\"{}\">\n",
        escape_xml_attr(&urn)
    ));
    xml.push_str(&format!(
        "      <origin hostname=\"{}\" />\n",
        escape_xml_attr(hostname)
    ));
    if let Some(payment) = payment {
        xml.push_str(&payment.to_xml());
    }
    // WOR-944: emit normative `<permits>`/`<prohibits>` for the
    // usage tier (from signals) and the user / geo tiers (from
    // operator vocab). Each pair is omitted entirely when its
    // tokens are empty so a silent tier produces no element.
    xml.push_str(&render_usage_tier(signals));
    if !vocab.user.is_silent() {
        xml.push_str(&render_tier_pair("user", &vocab.user));
    }
    if !vocab.geo.is_silent() {
        xml.push_str(&render_tier_pair("geo", &vocab.geo));
    }
    if let Some(directive) = signals.directive_value() {
        xml.push_str(&format!(
            "      <content-signal>{}</content-signal>\n",
            escape_xml_text(&directive)
        ));
    }
    xml.push_str("    </license>\n");
    xml.push_str("  </content>\n");
    xml.push_str("</rsl>\n");

    (xml, urn)
}

fn escape_xml_text(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            _ => out.push(c),
        }
    }
    out
}

fn escape_xml_attr(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn urn_format_matches_spec() {
        let (_xml, urn) = render("shop.example.com", Some("ai-train"), None, 42);
        assert_eq!(urn, "urn:rsl:1.0:shop.example.com:42");
    }

    #[test]
    fn ai_train_emits_permits_usage_ai_train() {
        let (xml, _) = render("h", Some("ai-train"), None, 1);
        // WOR-944: normative `<permits type="usage">` per RSL 1.0
        // §3.5; the legacy `<ai-use>` element does not exist in the
        // spec.
        assert!(
            xml.contains(r#"<permits type="usage">ai-train</permits>"#),
            "missing permits-usage; got:\n{xml}"
        );
        assert!(xml.contains("<content-signal>ai-train</content-signal>"));
    }

    #[test]
    fn ai_input_emits_permits_usage_ai_input() {
        let (xml, _) = render("h", Some("ai-input"), None, 1);
        assert!(xml.contains(r#"<permits type="usage">ai-input</permits>"#));
    }

    #[test]
    fn search_emits_permits_usage_search() {
        let (xml, _) = render("h", Some("search"), None, 1);
        assert!(xml.contains(r#"<permits type="usage">search</permits>"#));
    }

    #[test]
    fn absent_signal_omits_permits_and_prohibits() {
        // WOR-944 behavior change: the spec is silent-permissive when
        // no usage tokens are declared. We no longer synthesise a
        // default-deny `<ai-use licensed="false">` because that
        // element does not exist in the RSL 1.0 schema and the
        // synthesis was non-conformant to begin with.
        let (xml, _) = render("h", None, None, 1);
        assert!(!xml.contains("<permits"));
        assert!(!xml.contains("<prohibits"));
        assert!(!xml.contains("<content-signal>"));
    }

    #[test]
    fn unknown_signal_omits_permits_but_still_echoes_for_forensics() {
        // An unrecognised signal value (`custom-future-value`) is
        // outside the RSL §3.4.1.1 closed enum, so we cannot map it
        // to a token. Omit the usage tier silently; the sbproxy
        // extension `<content-signal>` still echoes the raw value
        // for the audit trail.
        let (xml, _) = render("h", Some("custom-future-value"), None, 1);
        assert!(!xml.contains("<permits"));
        assert!(!xml.contains("<prohibits"));
        assert!(xml.contains("<content-signal>custom-future-value</content-signal>"));
    }

    #[test]
    fn no_ai_use_element_ever_emitted_from_render() {
        // Regression guard for WOR-944. `<ai-use>` is not a normative
        // RSL 1.0 element; ensure no code path synthesises it.
        for sig in [Some("ai-train"), Some("ai-input"), Some("search"), None] {
            let (xml, _) = render("h", sig, None, 1);
            assert!(
                !xml.contains("<ai-use"),
                "render produced <ai-use> for signal {sig:?}: {xml}"
            );
        }
    }

    #[test]
    fn xml_namespace_is_canonical_rsl_collective() {
        let (xml, _) = render("h", Some("ai-train"), None, 1);
        assert!(xml.starts_with(r#"<?xml version="1.0" encoding="UTF-8"?>"#));
        assert!(
            xml.contains(r#"<rsl xmlns="https://rslstandard.org/rsl" version="1.0">"#),
            "namespace must be the canonical RSL Collective URI; got:\n{xml}"
        );
        // Make sure the legacy non-canonical namespace is gone.
        assert!(
            !xml.contains("rsl.ai/spec/1.0"),
            "legacy rsl.ai/spec/1.0 namespace must not appear"
        );
    }

    #[test]
    fn document_nests_license_under_content_with_url_attr() {
        let (xml, _) = render("shop.example.com", Some("ai-train"), None, 1);
        // The license body must live under a `<content url=...>`
        // element, not be a sibling of `<rsl>`.
        assert!(
            xml.contains(r#"<content url="https://shop.example.com/*">"#),
            "<content> element must wrap the license with a url attr; got:\n{xml}"
        );
        assert!(xml.contains("<license urn="));
        // Order: <rsl> -> <content> -> <license>.
        let rsl_idx = xml.find("<rsl ").expect("<rsl> present");
        let content_idx = xml.find("<content ").expect("<content> present");
        let license_idx = xml.find("<license ").expect("<license> present");
        assert!(
            rsl_idx < content_idx && content_idx < license_idx,
            "ordering must be <rsl> -> <content> -> <license>"
        );
        // Closing tags balance.
        assert!(xml.contains("</license>"));
        assert!(xml.contains("</content>"));
        assert!(xml.contains("</rsl>"));
    }

    #[test]
    fn hostname_with_special_chars_is_escaped_in_attr() {
        // Constructed (not realistic) hostname to verify the attribute
        // escaper is wired even though DNS hostnames cannot legally
        // contain `&`.
        let (xml, _) = render("a&b", Some("ai-train"), None, 1);
        assert!(xml.contains("hostname=\"a&amp;b\""));
        // The url attribute must also be escaped.
        assert!(xml.contains("url=\"https://a&amp;b/*\""));
    }

    #[test]
    fn deterministic_output() {
        let (a, _) = render("h", Some("ai-train"), None, 1);
        let (b, _) = render("h", Some("ai-train"), None, 1);
        assert_eq!(a, b);
    }

    #[test]
    fn payment_crawl_emits_type_amount_and_currency() {
        let p = PaymentTerms {
            payment_type: "crawl".to_string(),
            amount: Some(0.002),
            currency: Some("USD".to_string()),
            standard: None,
        };
        let (xml, _) = render("h", Some("ai-train"), Some(&p), 1);
        assert!(
            xml.contains(r#"<payment type="crawl" amount="0.002" currency="USD" />"#),
            "priced crawl payment emits amount + currency; got:\n{xml}"
        );
        // The <payment> element sits inside the <license> body.
        let pay_idx = xml.find("<payment ").expect("payment present");
        let lic_idx = xml.find("<license ").expect("license present");
        let close_idx = xml.find("</license>").expect("license close");
        assert!(lic_idx < pay_idx && pay_idx < close_idx);
    }

    #[test]
    fn payment_attribution_with_standard_emits_nested_standard_child() {
        // WOR-944: `<payment type="attribution">` switches to the
        // container form with a `<standard>` child when the operator
        // points at a reuse framework (CC-BY, etc.).
        let p = PaymentTerms {
            payment_type: "attribution".to_string(),
            amount: None,
            currency: None,
            standard: Some("https://creativecommons.org/licenses/by/4.0/".to_string()),
        };
        let (xml, _) = render("h", Some("ai-train"), Some(&p), 1);
        assert!(
            xml.contains(r#"<payment type="attribution">"#),
            "container open tag; got:\n{xml}"
        );
        assert!(
            xml.contains("<standard>https://creativecommons.org/licenses/by/4.0/</standard>"),
            "standard child must carry the URL verbatim; got:\n{xml}"
        );
        assert!(xml.contains("</payment>"));
    }

    #[test]
    fn payment_attribution_without_standard_emits_bare_self_closing() {
        // Backwards-compatible with PR #318: an attribution payment
        // without a `standard:` URL keeps the self-closing form.
        let p = PaymentTerms {
            payment_type: "attribution".to_string(),
            amount: None,
            currency: None,
            standard: None,
        };
        let (xml, _) = render("h", Some("ai-train"), Some(&p), 1);
        assert!(xml.contains(r#"<payment type="attribution" />"#));
        assert!(!xml.contains("<standard>"));
        assert!(!xml.contains("</payment>"));
    }

    #[test]
    fn payment_free_omits_amount_and_currency() {
        let (xml, _) = render("h", None, Some(&PaymentTerms::free()), 1);
        assert!(
            xml.contains(r#"<payment type="free" />"#),
            "free payment is bare; got:\n{xml}"
        );
        assert!(!xml.contains("amount="));
        assert!(!xml.contains("currency="));
    }

    #[test]
    fn payment_omitted_when_none() {
        let (xml, _) = render("h", Some("ai-train"), None, 1);
        assert!(!xml.contains("<payment"));
    }

    #[test]
    fn render_signals_emits_permits_and_prohibits_grouped_by_type() {
        // WOR-944: search=yes + ai_train=no splits the usage tier
        // into a `<permits type="usage">` (search) and a
        // `<prohibits type="usage">` (ai-train). ai_input undeclared
        // is silent (omitted from both).
        let signals = ContentSignals {
            search: Some(true),
            ai_input: None,
            ai_train: Some(false),
        };
        let (xml, urn) = render_signals("shop.example.com", &signals, None, 9);
        assert_eq!(urn, "urn:rsl:1.0:shop.example.com:9");
        assert!(
            xml.contains(r#"<permits type="usage">search</permits>"#),
            "search=yes -> permits-usage; got:\n{xml}"
        );
        assert!(
            xml.contains(r#"<prohibits type="usage">ai-train</prohibits>"#),
            "ai-train=no -> prohibits-usage; got:\n{xml}"
        );
        assert!(
            !xml.contains("ai-input"),
            "undeclared signal must be silent"
        );
        // Directive echoed for forensics.
        assert!(xml.contains("<content-signal>search=yes, ai-train=no</content-signal>"));
    }

    #[test]
    fn render_signals_is_consistent_with_robots_directive() {
        // The RSL `<permits>` set and the robots directive both
        // derive from the same ContentSignals, so a `search=yes` can
        // never appear inside `<prohibits>`.
        let signals = ContentSignals {
            search: Some(true),
            ai_input: Some(true),
            ai_train: Some(false),
        };
        let (xml, _) = render_signals("h", &signals, None, 1);
        // Permits and prohibits are each rendered as one element
        // per type=usage; the token order matches ContentSignals's
        // fixed iteration order (search, ai-input, ai-train).
        assert!(xml.contains(r#"<permits type="usage">search ai-input</permits>"#));
        assert!(xml.contains(r#"<prohibits type="usage">ai-train</prohibits>"#));
        assert_eq!(
            signals.directive_value().as_deref(),
            Some("search=yes, ai-input=yes, ai-train=no")
        );
    }

    #[test]
    fn render_signals_with_vocab_emits_user_tier() {
        // WOR-944: declared user vocab (RSL §3.4.1.2 audience tokens)
        // becomes `<permits type="user">` / `<prohibits type="user">`.
        let signals = ContentSignals::default();
        let vocab = RslVocab {
            user: TokenTier {
                permit: vec!["non-commercial".to_string(), "education".to_string()],
                prohibit: vec!["commercial".to_string()],
            },
            geo: TokenTier::default(),
        };
        let (xml, _) = render_signals_with_vocab("h", &signals, None, &vocab, 1);
        assert!(
            xml.contains(r#"<permits type="user">non-commercial education</permits>"#),
            "user permits; got:\n{xml}"
        );
        assert!(
            xml.contains(r#"<prohibits type="user">commercial</prohibits>"#),
            "user prohibits; got:\n{xml}"
        );
        // Geo silent -> no geo element.
        assert!(!xml.contains(r#"type="geo""#));
    }

    #[test]
    fn render_signals_with_vocab_emits_geo_tier() {
        let signals = ContentSignals::default();
        let vocab = RslVocab {
            user: TokenTier::default(),
            geo: TokenTier {
                permit: vec!["US".to_string(), "CA".to_string(), "GB".to_string()],
                prohibit: vec![],
            },
        };
        let (xml, _) = render_signals_with_vocab("h", &signals, None, &vocab, 1);
        assert!(
            xml.contains(r#"<permits type="geo">US CA GB</permits>"#),
            "geo permits; got:\n{xml}"
        );
        // Empty prohibit -> no prohibits-geo element.
        assert!(!xml.contains(r#"<prohibits type="geo""#));
    }

    #[test]
    fn render_signals_with_empty_vocab_matches_render_signals() {
        // A silent vocab must produce byte-identical output to the
        // legacy `render_signals` (no extra elements snuck in).
        let signals = ContentSignals {
            search: Some(true),
            ai_input: None,
            ai_train: Some(false),
        };
        let (legacy, _) = render_signals("h", &signals, None, 1);
        let (with_vocab, _) =
            render_signals_with_vocab("h", &signals, None, &RslVocab::default(), 1);
        assert_eq!(legacy, with_vocab);
    }

    #[test]
    fn render_signals_with_neither_tier_set_emits_only_origin_and_payment() {
        // Empty signals AND empty vocab => the `<license>` body has
        // only the `<origin>` element (and the optional `<payment>`
        // when supplied). No `<permits>`, no `<prohibits>`, no
        // legacy `<ai-use>`.
        let (xml, _) = render_signals_with_vocab(
            "h",
            &ContentSignals::default(),
            Some(&PaymentTerms::free()),
            &RslVocab::default(),
            1,
        );
        assert!(!xml.contains("<permits"));
        assert!(!xml.contains("<prohibits"));
        assert!(!xml.contains("<ai-use"));
        assert!(xml.contains(r#"<origin hostname="h" />"#));
        assert!(xml.contains(r#"<payment type="free" />"#));
    }

    #[test]
    fn no_ai_use_element_ever_emitted_from_render_signals() {
        // Regression guard for WOR-944: every shape that flows
        // through `render_signals` / `render_signals_with_vocab`
        // must produce zero `<ai-use>` substrings.
        let cases = [
            (ContentSignals::default(), RslVocab::default()),
            (
                ContentSignals {
                    search: Some(true),
                    ai_input: Some(false),
                    ai_train: Some(true),
                },
                RslVocab::default(),
            ),
            (
                ContentSignals::default(),
                RslVocab {
                    user: TokenTier {
                        permit: vec!["personal".to_string()],
                        prohibit: vec![],
                    },
                    geo: TokenTier {
                        permit: vec!["US".to_string()],
                        prohibit: vec!["RU".to_string()],
                    },
                },
            ),
        ];
        for (sig, vocab) in cases {
            let (xml, _) = render_signals_with_vocab("h", &sig, None, &vocab, 1);
            assert!(
                !xml.contains("<ai-use"),
                "render_signals_with_vocab produced <ai-use>; sig={sig:?}, vocab={vocab:?}; xml:\n{xml}"
            );
        }
    }

    // --- WOR-808 two-license-tier vocabulary ---

    fn tier(name: &str, ptype: &str, amount: f64, currency: &str) -> LicenseTier {
        LicenseTier {
            name: name.to_string(),
            payment: PaymentTerms {
                payment_type: ptype.to_string(),
                amount: Some(amount),
                currency: Some(currency.to_string()),
                standard: None,
            },
            signals: ContentSignals {
                search: Some(true),
                ai_input: Some(true),
                ai_train: None,
            },
        }
    }

    #[test]
    fn render_tiered_emits_one_license_per_tier_with_distinct_urn_fragments() {
        let tiers = vec![
            tier("summarize", "crawl", 0.002, "USD"),
            tier("full-display", "crawl", 0.010, "USD"),
        ];
        let (xml, primary_urn) = render_tiered("shop.example.com", &tiers, &RslVocab::default(), 7);
        assert_eq!(primary_urn, "urn:rsl:1.0:shop.example.com:7");
        // One <content> wraps both tiers (a TollBit marketplace can
        // pick the tier appropriate to the use case from one fetch).
        assert_eq!(xml.matches("<content ").count(), 1);
        assert_eq!(xml.matches("<license ").count(), 2);
        assert!(xml.contains(r#"urn="urn:rsl:1.0:shop.example.com:7#summarize""#));
        assert!(xml.contains(r#"urn="urn:rsl:1.0:shop.example.com:7#full-display""#));
        // The two tiers price independently.
        assert!(xml.contains(r#"amount="0.002""#));
        assert!(xml.contains(r#"amount="0.01""#));
    }

    #[test]
    fn render_tiered_propagates_user_and_geo_vocab_into_each_license() {
        let tiers = vec![
            tier("summarize", "crawl", 0.002, "USD"),
            tier("full-display", "crawl", 0.010, "USD"),
        ];
        let vocab = RslVocab {
            user: TokenTier {
                permit: vec!["commercial".to_string()],
                prohibit: vec![],
            },
            geo: TokenTier {
                permit: vec!["US".to_string(), "CA".to_string()],
                prohibit: vec![],
            },
        };
        let (xml, _) = render_tiered("shop.example.com", &tiers, &vocab, 1);
        // user + geo vocab is origin-wide; each <license> repeats
        // them so a tier consumer reads them off its own URN.
        assert_eq!(
            xml.matches(r#"<permits type="user">commercial</permits>"#)
                .count(),
            2
        );
        assert_eq!(
            xml.matches(r#"<permits type="geo">US CA</permits>"#)
                .count(),
            2
        );
    }

    #[test]
    fn render_tiered_emits_per_tier_signals_inside_their_own_license() {
        // The first tier permits ai-input + search; the second adds
        // ai-train. Both must render inside their own <license> body
        // so a consumer reading one tier never sees the other tier's
        // signals.
        let cheap = LicenseTier {
            name: "summarize".to_string(),
            payment: PaymentTerms::free(),
            signals: ContentSignals {
                search: Some(true),
                ai_input: Some(true),
                ai_train: None,
            },
        };
        let pricey = LicenseTier {
            name: "full-display".to_string(),
            payment: PaymentTerms::free(),
            signals: ContentSignals {
                search: Some(true),
                ai_input: Some(true),
                ai_train: Some(true),
            },
        };
        let (xml, _) = render_tiered("h", &[cheap, pricey], &RslVocab::default(), 1);
        // Extract the body between the two <license ...> tags. The
        // first license body is everything up to "</license>"; the
        // second is everything between the second "<license " and
        // the final "</license>". A naive split is fine since the
        // renderer is deterministic.
        let first_close = xml.find("</license>").expect("first close");
        let first_body = &xml[..first_close];
        let after_first = &xml[first_close + "</license>".len()..];
        let second_open = after_first.find("<license ").expect("second open");
        let second_body = &after_first[second_open..];
        assert!(first_body.contains("search ai-input"));
        assert!(!first_body.contains("ai-train"));
        assert!(second_body.contains("ai-train"));
    }

    #[test]
    fn render_tiered_escapes_xml_metacharacters_in_tier_name() {
        // Operator misconfigures a tier name with `<` or `"`. The URN
        // attribute MUST escape those characters so the resulting XML
        // stays parseable.
        let t = LicenseTier {
            name: "weird\"<name>".to_string(),
            payment: PaymentTerms::free(),
            signals: ContentSignals::default(),
        };
        let (xml, _) = render_tiered("h", &[t], &RslVocab::default(), 1);
        assert!(!xml.contains("\"<name>"));
        assert!(xml.contains("weird&quot;&lt;name&gt;"));
    }
}
