//! G4.5: `robots.txt` projection per IETF draft-koster-rep-ai.
//!
//! Format:
//!
//! ```text
//! # Generated by SBproxy. Do not edit.
//! # Config version: <hash>
//!
//! User-agent: GPTBot
//! Disallow: /premium/*
//! Crawl-delay: 1
//! # SBproxy-AI-Extension: pay-per-crawl price=0.001 currency=USD shape=html
//!
//! User-agent: *
//! Disallow:
//! ```
//!
//! One stanza per agent class with a Disallow rule, derived by walking
//! the operator's `Tier` array and emitting a stanza per agent that
//! has at least one priced tier (`price.amount_micros > 0`). The
//! `# SBproxy-AI-Extension:` comment lines carry pricing metadata for
//! cooperative crawlers; the prefix is intentionally non-standard
//! pending IETF standardisation.

use std::collections::BTreeMap;

use serde_json::Value;

/// Render the `robots.txt` body for a single origin.
///
/// `ai_crawl` is the JSON snapshot of the origin's
/// `ai_crawl_control` policy entry. The function walks
/// `ai_crawl["tiers"]` and emits one User-agent stanza per distinct
/// `agent_id` selector (with `*` as the wildcard).
pub fn render(_hostname: &str, ai_crawl: &Value, config_version: u64) -> String {
    let mut out = String::with_capacity(512);
    out.push_str("# Generated by SBproxy. Do not edit.\n");
    out.push_str(&format!("# Config version: {config_version}\n\n"));

    // Group tiers by agent class. Map preserves insertion order via
    // BTreeMap on the agent name (alphabetised); deterministic output
    // matters for snapshot tests.
    //
    // Key: agent class (`*` for wildcard / no selector).
    // Value: list of (route_pattern, price_units, currency, shape).
    let mut by_agent: BTreeMap<String, Vec<TierEntry>> = BTreeMap::new();

    if let Some(tiers) = ai_crawl.get("tiers").and_then(|v| v.as_array()) {
        for tier in tiers {
            let route = tier
                .get("route_pattern")
                .and_then(|v| v.as_str())
                .unwrap_or("/")
                .to_string();
            let price_units = tier
                .get("price")
                .and_then(|p| p.get("amount_micros"))
                .and_then(|v| v.as_u64())
                .or_else(|| {
                    // Fallback: pre-compile YAML may carry `price` as
                    // a flat number (the AiCrawlControlConfig top-level
                    // field). The Tier shape uses `Money { amount_micros }`
                    // post-deserialise; until G4.2 wires the unified
                    // shape we accept either.
                    tier.get("price")
                        .and_then(|v| v.as_f64())
                        .map(|f| (f.max(0.0) * 1_000_000.0).round() as u64)
                });
            let Some(micros) = price_units else { continue };
            if micros == 0 {
                // Free tiers do not contribute a Disallow stanza; the
                // crawler can fetch them under the catch-all rule.
                continue;
            }
            let currency = tier
                .get("price")
                .and_then(|p| p.get("currency"))
                .and_then(|v| v.as_str())
                .unwrap_or("USD")
                .to_string();
            let shape = tier
                .get("content_shape")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string());
            let agent = tier
                .get("agent_id")
                .and_then(|v| v.as_str())
                .filter(|s| !s.is_empty())
                .unwrap_or("*")
                .to_string();
            by_agent.entry(agent).or_default().push(TierEntry {
                route,
                price_micros: micros,
                currency,
                shape,
            });
        }
    }

    // Top-level fallback price (Wave 1 single-tier shape). When set,
    // it expresses a "pay for any path" Disallow against the wildcard
    // agent; the crawler may still negotiate the matched tiers above.
    let top_price = ai_crawl
        .get("price")
        .and_then(|v| v.as_f64())
        .map(|f| (f.max(0.0) * 1_000_000.0).round() as u64)
        .unwrap_or(0);
    let top_currency = ai_crawl
        .get("currency")
        .and_then(|v| v.as_str())
        .unwrap_or("USD")
        .to_string();

    // --- Emit per-agent stanzas ---
    for (agent, tiers) in &by_agent {
        out.push_str(&format!("User-agent: {agent}\n"));
        for tier in tiers {
            out.push_str(&format!("Disallow: {}\n", tier.route));
            out.push_str("Crawl-delay: 1\n");
            let price = format_units(tier.price_micros);
            let shape = tier.shape.as_deref().unwrap_or("any");
            out.push_str(&format!(
                "# SBproxy-AI-Extension: pay-per-crawl price={price} currency={} shape={shape}\n",
                tier.currency
            ));
        }
        out.push('\n');
    }

    // --- Catch-all stanza ---
    //
    // Emitted unconditionally so well-behaved crawlers still receive
    // a `User-agent: *` block. When a top-level price is configured
    // (Wave 1 single-tier shape) we surface it on the wildcard
    // stanza; otherwise we serve an empty Disallow line.
    out.push_str("User-agent: *\n");
    if top_price > 0 && !by_agent.contains_key("*") {
        out.push_str("Disallow: /\n");
        out.push_str("Crawl-delay: 1\n");
        let price = format_units(top_price);
        out.push_str(&format!(
            "# SBproxy-AI-Extension: pay-per-crawl price={price} currency={top_currency} shape=any\n"
        ));
    } else {
        out.push_str("Disallow:\n");
    }

    out
}

struct TierEntry {
    route: String,
    price_micros: u64,
    currency: String,
    shape: Option<String>,
}

fn format_units(micros: u64) -> String {
    let major = micros / 1_000_000;
    let minor = micros % 1_000_000;
    format!("{major}.{minor:06}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_tiers_emits_only_catch_all() {
        let cfg = serde_json::json!({"type": "ai_crawl_control"});
        let body = render("a.example.com", &cfg, 1);
        assert!(body.contains("# Config version: 1"));
        assert!(body.contains("User-agent: *"));
        assert!(body.contains("Disallow:\n"));
        assert!(!body.contains("SBproxy-AI-Extension"));
    }

    #[test]
    fn single_tier_with_default_agent_emits_wildcard_stanza() {
        let cfg = serde_json::json!({
            "type": "ai_crawl_control",
            "tiers": [{
                "route_pattern": "/premium/*",
                "price": {"amount_micros": 1000, "currency": "USD"},
                "content_shape": "html",
            }],
        });
        let body = render("shop.example.com", &cfg, 42);
        assert!(body.contains("# Config version: 42"));
        assert!(body.contains("User-agent: *\nDisallow: /premium/*"));
        assert!(body.contains("Crawl-delay: 1"));
        assert!(body.contains(
            "# SBproxy-AI-Extension: pay-per-crawl price=0.001000 currency=USD shape=html"
        ));
    }

    #[test]
    fn multiple_agent_classes_emit_separate_stanzas() {
        let cfg = serde_json::json!({
            "type": "ai_crawl_control",
            "tiers": [
                {
                    "route_pattern": "/articles/*",
                    "price": {"amount_micros": 2000, "currency": "USD"},
                    "agent_id": "GPTBot",
                    "content_shape": "html",
                },
                {
                    "route_pattern": "/data/*",
                    "price": {"amount_micros": 5000, "currency": "USD"},
                    "agent_id": "ClaudeBot",
                    "content_shape": "json",
                },
            ],
        });
        let body = render("api.example.com", &cfg, 7);
        assert!(body.contains("User-agent: ClaudeBot"));
        assert!(body.contains("User-agent: GPTBot"));
        // Wildcard stanza should still be present at the end.
        let wildcard_idx = body.find("User-agent: *").expect("wildcard present");
        let gpt_idx = body.find("User-agent: GPTBot").expect("gpt present");
        assert!(
            wildcard_idx > gpt_idx,
            "wildcard stanza should come after agent-specific stanzas"
        );
    }

    #[test]
    fn free_tier_does_not_emit_disallow() {
        let cfg = serde_json::json!({
            "type": "ai_crawl_control",
            "tiers": [{
                "route_pattern": "/free/*",
                "price": {"amount_micros": 0, "currency": "USD"},
            }],
        });
        let body = render("h.example.com", &cfg, 1);
        assert!(!body.contains("/free/*"));
    }

    #[test]
    fn top_level_price_emits_wildcard_disallow() {
        let cfg = serde_json::json!({
            "type": "ai_crawl_control",
            "price": 0.001,
            "currency": "USD",
        });
        let body = render("h.example.com", &cfg, 5);
        assert!(body.contains("User-agent: *\nDisallow: /\nCrawl-delay: 1"));
        assert!(body.contains("price=0.001000 currency=USD shape=any"));
    }

    #[test]
    fn deterministic_output_for_same_input() {
        let cfg = serde_json::json!({
            "type": "ai_crawl_control",
            "tiers": [
                {"route_pattern": "/a/*", "price": {"amount_micros": 1000, "currency": "USD"}, "agent_id": "Beta"},
                {"route_pattern": "/b/*", "price": {"amount_micros": 1000, "currency": "USD"}, "agent_id": "Alpha"},
            ],
        });
        let body1 = render("h", &cfg, 1);
        let body2 = render("h", &cfg, 1);
        assert_eq!(body1, body2, "render must be deterministic");
        // BTreeMap orders alphabetically: Alpha before Beta.
        let alpha = body1.find("User-agent: Alpha").unwrap();
        let beta = body1.find("User-agent: Beta").unwrap();
        assert!(alpha < beta);
    }
}
