//! Pluggable SSE usage parsers for AI providers.
//!
//! Different providers report token usage with different SSE shapes
//! (OpenAI puts a terminal `usage` chunk on the wire, Anthropic
//! splits it across `message_start` / `message_delta`, Vertex emits
//! `usageMetadata`, Bedrock wraps each Anthropic chunk in a
//! base64-encoded `bytes` envelope, Cohere uses an `event-type`
//! taxonomy, Ollama emits line-delimited JSON). The streaming relay
//! in `sbproxy-core` does not want to know about any of those
//! shapes; it just needs a parser to feed bytes into and ask for
//! totals at stream close.
//!
//! The [`SseUsageParser`] trait is the contract. One implementation
//! per provider lives under `usage_parser::<provider>`; the
//! [`select_parser`] entry point returns a boxed parser based on the
//! configured `usage_parser` field plus runtime hints (upstream URL,
//! response Content-Type, optional `X-Provider` header).
//!
//! All implementations buffer at most a single SSE line so streams of
//! arbitrary length never accumulate the full response body in
//! memory. Parse failures and missing usage fields are silently
//! ignored: streams routinely interleave keep-alive comments and
//! events without any usage payload, and a malformed upstream chunk
//! must never abort the relay.

pub mod anthropic;
pub mod bedrock;
pub mod cohere;
pub mod generic;
pub mod ollama;
pub mod openai;
pub mod vertex;

pub use anthropic::AnthropicUsageParser;
pub use bedrock::BedrockUsageParser;
pub use cohere::CohereUsageParser;
pub use generic::GenericUsageParser;
pub use ollama::OllamaUsageParser;
pub use openai::OpenAiUsageParser;
pub use vertex::VertexUsageParser;

/// Snapshot of token counts captured from an SSE stream.
///
/// Returned by [`SseUsageParser::snapshot`] when at least one usage
/// block has been observed. `None` from the parser means "no usage
/// seen yet" and the caller must treat the stream as unbilled.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct UsageTokens {
    /// Tokens consumed by the input (prompt / system / context).
    pub prompt_tokens: u32,
    /// Tokens generated by the model in the response.
    pub completion_tokens: u32,
}

/// Pluggable SSE usage parser.
///
/// Implementations maintain their own line buffer so callers can
/// hand them arbitrary chunk boundaries (frames may arrive split or
/// coalesced from upstream).
///
/// The trait is `Send + Sync` because the streaming relay holds the
/// parser across `await` points and may move it across tasks.
pub trait SseUsageParser: Send + Sync {
    /// Feed one chunk of stream bytes. The parser is responsible for
    /// re-joining partial lines across `feed` calls.
    fn feed(&mut self, chunk: &[u8]);

    /// Snapshot the current best-known token counts. Called once on
    /// stream close. Returns `None` when no usage block has been
    /// observed (e.g. truncated stream or provider that never emits
    /// usage on the wire).
    fn snapshot(&self) -> Option<UsageTokens>;

    /// Provider tag, used for metrics and logging.
    fn provider(&self) -> &'static str;
}

/// Configured `usage_parser` value plus the runtime hints needed to
/// resolve `auto`. Bundled into a struct so the call site at
/// `relay_ai_stream` does not have to plumb four loose arguments
/// into `select_parser`.
#[derive(Debug, Clone, Default)]
pub struct UsageParserHints<'a> {
    /// Upstream URL hostname (e.g. `api.openai.com`,
    /// `generativelanguage.googleapis.com`). Used by `auto` to map a
    /// known host to a parser.
    pub upstream_host: Option<&'a str>,
    /// Response `Content-Type` header. SSE responses are
    /// `text/event-stream` regardless of provider, but a few
    /// providers (Ollama) use `application/x-ndjson` which is a
    /// strong hint by itself.
    pub content_type: Option<&'a str>,
    /// Optional `X-Provider` response header. When upstream sets it,
    /// it overrides URL-host inference.
    pub x_provider: Option<&'a str>,
}

/// Build a usage parser for the streaming relay.
///
/// `configured` is the operator-provided `usage_parser` value
/// (`auto`, `openai`, `anthropic`, `vertex`, `bedrock`, `cohere`,
/// `ollama`, `generic`, or `none`). Unknown values fall back to
/// `GenericUsageParser` after a one-time warn so a typo never
/// silently disables billing.
///
/// Returns `None` only when `configured == "none"`. Every other
/// branch yields a live parser; the relay then unconditionally feeds
/// chunks and reads the snapshot at stream close.
pub fn select_parser(
    configured: &str,
    hints: &UsageParserHints<'_>,
) -> Option<Box<dyn SseUsageParser>> {
    match configured.trim().to_ascii_lowercase().as_str() {
        "none" => None,
        "openai" => Some(Box::new(OpenAiUsageParser::new())),
        "anthropic" => Some(Box::new(AnthropicUsageParser::new())),
        "vertex" | "gemini" => Some(Box::new(VertexUsageParser::new())),
        "bedrock" => Some(Box::new(BedrockUsageParser::new())),
        "cohere" => Some(Box::new(CohereUsageParser::new())),
        "ollama" => Some(Box::new(OllamaUsageParser::new())),
        "generic" => Some(Box::new(GenericUsageParser::new())),
        "" | "auto" => Some(auto_select(hints)),
        other => {
            tracing::warn!(
                value = %other,
                "unknown usage_parser value; falling back to generic"
            );
            Some(Box::new(GenericUsageParser::new()))
        }
    }
}

/// Choose a parser based on runtime hints.
///
/// Order of precedence:
/// 1. Explicit `X-Provider` response header (operator-controlled).
/// 2. Upstream URL host (well-known mappings).
/// 3. Response `Content-Type` (Ollama's `application/x-ndjson`).
/// 4. Fallback to [`GenericUsageParser`].
fn auto_select(hints: &UsageParserHints<'_>) -> Box<dyn SseUsageParser> {
    if let Some(tag) = hints.x_provider {
        if let Some(p) = parser_for_tag(tag) {
            return p;
        }
    }
    if let Some(host) = hints.upstream_host {
        if let Some(p) = parser_for_host(host) {
            return p;
        }
    }
    if let Some(ct) = hints.content_type {
        let lc = ct.to_ascii_lowercase();
        if lc.contains("application/x-ndjson") || lc.contains("application/jsonl") {
            return Box::new(OllamaUsageParser::new());
        }
    }
    Box::new(GenericUsageParser::new())
}

/// Map a free-form provider tag (from `X-Provider`) to a parser.
fn parser_for_tag(tag: &str) -> Option<Box<dyn SseUsageParser>> {
    let lc = tag.trim().to_ascii_lowercase();
    let p: Box<dyn SseUsageParser> = match lc.as_str() {
        "openai" | "azure-openai" | "azure" => Box::new(OpenAiUsageParser::new()),
        "anthropic" => Box::new(AnthropicUsageParser::new()),
        "vertex" | "gemini" | "google" | "vertex-ai" => Box::new(VertexUsageParser::new()),
        "bedrock" | "aws-bedrock" => Box::new(BedrockUsageParser::new()),
        "cohere" => Box::new(CohereUsageParser::new()),
        "ollama" => Box::new(OllamaUsageParser::new()),
        _ => return None,
    };
    Some(p)
}

/// Map an upstream hostname to a parser. Substring matching keeps
/// the table compact and tolerates regional subdomains
/// (`us-central1-aiplatform.googleapis.com`, etc.).
fn parser_for_host(host: &str) -> Option<Box<dyn SseUsageParser>> {
    let lc = host.to_ascii_lowercase();
    if lc.contains("openai.com") || lc.contains("openai.azure.com") {
        return Some(Box::new(OpenAiUsageParser::new()));
    }
    if lc.contains("anthropic.com") {
        return Some(Box::new(AnthropicUsageParser::new()));
    }
    if lc.contains("googleapis.com") || lc.contains("aiplatform") {
        return Some(Box::new(VertexUsageParser::new()));
    }
    if lc.contains("bedrock") || lc.contains("amazonaws.com") {
        return Some(Box::new(BedrockUsageParser::new()));
    }
    if lc.contains("cohere.ai") || lc.contains("cohere.com") {
        return Some(Box::new(CohereUsageParser::new()));
    }
    if lc.contains("ollama") || lc.contains("localhost:11434") || lc.contains("127.0.0.1:11434") {
        return Some(Box::new(OllamaUsageParser::new()));
    }
    None
}

/// Internal helper used by every line-buffered parser. Splits a
/// chunk on `\n` boundaries, calls `on_line` for each completed
/// line, and stashes the trailing partial line into `buf` for the
/// next call.
///
/// The per-line buffer is capped at 64 KiB so a malformed upstream
/// cannot grow it without bound. Real SSE lines are well under 8
/// KiB; the ceiling is generous on purpose.
pub(crate) fn feed_lines(buf: &mut Vec<u8>, chunk: &[u8], mut on_line: impl FnMut(&[u8])) {
    const MAX_LINE: usize = 64 * 1024;
    for byte in chunk {
        if *byte == b'\n' {
            on_line(buf);
            buf.clear();
        } else if *byte != b'\r' && buf.len() < MAX_LINE {
            buf.push(*byte);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn select_parser_handles_explicit_values() {
        let hints = UsageParserHints::default();
        assert_eq!(
            select_parser("openai", &hints).as_ref().unwrap().provider(),
            "openai"
        );
        assert_eq!(
            select_parser("anthropic", &hints)
                .as_ref()
                .unwrap()
                .provider(),
            "anthropic"
        );
        assert_eq!(
            select_parser("vertex", &hints).as_ref().unwrap().provider(),
            "vertex"
        );
        assert_eq!(
            select_parser("bedrock", &hints)
                .as_ref()
                .unwrap()
                .provider(),
            "bedrock"
        );
        assert_eq!(
            select_parser("cohere", &hints).as_ref().unwrap().provider(),
            "cohere"
        );
        assert_eq!(
            select_parser("ollama", &hints).as_ref().unwrap().provider(),
            "ollama"
        );
        assert_eq!(
            select_parser("generic", &hints)
                .as_ref()
                .unwrap()
                .provider(),
            "generic"
        );
    }

    #[test]
    fn select_parser_none_returns_no_parser() {
        let hints = UsageParserHints::default();
        assert!(select_parser("none", &hints).is_none());
    }

    #[test]
    fn select_parser_unknown_falls_back_to_generic() {
        let hints = UsageParserHints::default();
        let p = select_parser("totally-made-up", &hints).unwrap();
        assert_eq!(p.provider(), "generic");
    }

    #[test]
    fn auto_uses_x_provider_header_first() {
        let hints = UsageParserHints {
            upstream_host: Some("api.openai.com"),
            x_provider: Some("anthropic"),
            ..Default::default()
        };
        let p = select_parser("auto", &hints).unwrap();
        assert_eq!(p.provider(), "anthropic");
    }

    #[test]
    fn auto_falls_back_to_host() {
        let hints = UsageParserHints {
            upstream_host: Some("generativelanguage.googleapis.com"),
            ..Default::default()
        };
        assert_eq!(select_parser("auto", &hints).unwrap().provider(), "vertex");

        let hints = UsageParserHints {
            upstream_host: Some("api.cohere.ai"),
            ..Default::default()
        };
        assert_eq!(select_parser("auto", &hints).unwrap().provider(), "cohere");

        let hints = UsageParserHints {
            upstream_host: Some("api.anthropic.com"),
            ..Default::default()
        };
        assert_eq!(
            select_parser("auto", &hints).unwrap().provider(),
            "anthropic"
        );

        let hints = UsageParserHints {
            upstream_host: Some("bedrock-runtime.us-east-1.amazonaws.com"),
            ..Default::default()
        };
        assert_eq!(select_parser("auto", &hints).unwrap().provider(), "bedrock");
    }

    #[test]
    fn auto_falls_back_to_content_type_for_ndjson() {
        let hints = UsageParserHints {
            content_type: Some("application/x-ndjson"),
            ..Default::default()
        };
        assert_eq!(select_parser("auto", &hints).unwrap().provider(), "ollama");
    }

    #[test]
    fn auto_falls_back_to_generic_when_no_hints() {
        let hints = UsageParserHints::default();
        assert_eq!(select_parser("auto", &hints).unwrap().provider(), "generic");
    }

    #[test]
    fn feed_lines_splits_on_newlines_and_strips_cr() {
        let mut buf = Vec::new();
        let mut lines: Vec<Vec<u8>> = Vec::new();
        feed_lines(&mut buf, b"a\r\nbb\nccc", |line| lines.push(line.to_vec()));
        assert_eq!(lines, vec![b"a".to_vec(), b"bb".to_vec()]);
        assert_eq!(buf, b"ccc");
    }

    #[test]
    fn feed_lines_caps_runaway_line() {
        let mut buf = Vec::new();
        let big = vec![b'x'; 200 * 1024];
        feed_lines(&mut buf, &big, |_| {});
        assert!(buf.len() <= 64 * 1024);
    }
}
