apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-default
  namespace: soapbucket
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: proxy-shared-fleet
      port:
        number: 80
