#!/usr/bin/env python3
"""Generate VHS cassettes for sbproxy examples from their documented curls.

For each example under examples/, this reads the `Test:` block in the
sb.yml header comment, extracts up to a few command units (curl / for-loop),
normalizes them to single lines, fixes deprecated model ids, and writes a
tape under docs/tapes/<example>.tape with a `# CONFIG:` directive that
scripts/record-tapes.sh understands.

Examples that need external services (redis, embedding sidecar, vault, TLS,
mTLS, ONNX weights) are skipped: they cannot run standalone in a recording.
The four hand-authored headline tapes are also skipped.

Usage:
  scripts/gen-example-tapes.py            # generate for all runnable examples
  scripts/gen-example-tapes.py --list     # print the plan (generate/skip) only
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXAMPLES = os.path.join(ROOT, "examples")
TAPES = os.path.join(ROOT, "docs", "tapes")

# Hand-authored, do not overwrite.
HEADLINE = {"ai-gateway-quickstart", "ai-routing-fallback",
            "semantic-cache-openai", "ai-guardrails"}

# Markers that mean the example needs a service we can't spin up in a tape.
EXTERNAL = re.compile(
    r"\b(redis|memcached|sidecar|classifier|vault://|onnx|\.onnx|"
    r"tls:|mtls|mutual_tls|client_cert|cert_file|key_file)\b", re.I)

# Deprecated model ids -> current ones.
MODEL_FIXES = [
    (re.compile(r"claude-3-5-sonnet-latest|claude-3-5-sonnet-\d+"), "claude-haiku-4-5"),
    (re.compile(r"claude-3-5-haiku-latest|claude-3-5-haiku-\d+"), "claude-haiku-4-5"),
    (re.compile(r"claude-3-opus-latest|claude-3-opus-\d+"), "claude-haiku-4-5"),
    (re.compile(r"gemini-2\.\d+-flash|gemini-1\.5-[a-z]+|gemini-flash-latest"), "gemini-3.5-flash"),
]

# Shell vars the record script provides (from test/.env). A demo that needs
# any other $VAR / ${VAR} can't run cleanly in a recording, so skip it.
ALLOWED_VARS = {"ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY"}
UNDEF_VAR = re.compile(r"\$\{?([A-Z_][A-Z0-9_]*)\}?")

GEN_MARKER = "Auto-generated by scripts/gen-example-tapes.py"

THEME = ('{ "name": "sbproxy", "background": "#0d0d0f", "foreground": "#e6e6e6", '
         '"cursor": "#ffb454", "selection": "#2a2a33", "black": "#1a1a1f", '
         '"red": "#ff6b6b", "green": "#a8d96a", "yellow": "#ffb454", "blue": "#7aa2f7", '
         '"magenta": "#bb9af7", "cyan": "#7dcfff", "white": "#e6e6e6", '
         '"brightBlack": "#5c5c66", "brightRed": "#ff8888", "brightGreen": "#c3f088", '
         '"brightYellow": "#ffd194", "brightBlue": "#9bb8ff", "brightMagenta": "#d4b8ff", '
         '"brightCyan": "#a4e0ff", "brightWhite": "#ffffff" }')


def header_lines(sb_path):
    """Return the leading comment block of an sb.yml as raw text lines."""
    out = []
    with open(sb_path) as f:
        for line in f:
            s = line.rstrip("\n")
            if s.startswith("#"):
                out.append(s)
            elif s.strip() == "":
                out.append("")
            else:
                break  # first non-comment, non-blank line ends the header
    return out


def strip_comment(line):
    """Drop a leading '# ' / '#' from a header comment line."""
    if line.startswith("# "):
        return line[2:]
    if line.startswith("#"):
        return line[1:]
    return line


def extract_commands(hdr, max_cmds=2):
    """Pull up to max_cmds runnable command units from the Test: block."""
    # Find the Test: marker.
    start = None
    for i, line in enumerate(hdr):
        if re.match(r"#\s*Test\b", line) or re.match(r"#\s*Try\b", line):
            start = i + 1
            break
    if start is None:
        return []

    # Body of the test block: comment lines until a new section header.
    body = []
    for line in hdr[start:]:
        if line == "":
            continue
        text = strip_comment(line)
        # Stop at a new top-level section like "Expected", "Run:", "Note".
        if re.match(r"^[A-Z][A-Za-z ]+:\s*$", text.strip()) and not text.strip().startswith("#"):
            break
        body.append(text)

    # Group lines into command units.
    cmds = []
    cur = []
    in_loop = 0
    for raw in body:
        t = raw.strip()
        if not t:
            continue
        # Skip pure annotation comments (# => ..., # expect ...).
        if t.startswith("#"):
            if cur:  # comment inside a command unit: ignore
                continue
            continue
        if cur:
            cur.append(t)
        else:
            if t.startswith(("curl", "for", "while", "(", "seq", "echo", "http")) or "curl" in t:
                cur = [t]
            else:
                continue
        if re.search(r"\bfor\b.*\bdo\b", t) or t.endswith("do"):
            in_loop += 1
        if t.startswith("done") or t == "done" or t.endswith("done"):
            in_loop = max(0, in_loop - 1)
        cont = t.endswith("\\")
        # A command unit is complete only when it is not a backslash
        # continuation, no loop is open, and its quotes balance. The last
        # rule keeps multi-line `-d '{ ... }'` JSON bodies (which span comment
        # lines with no trailing backslash) joined into one command.
        joined = " ".join(x.rstrip("\\").strip() for x in cur)
        balanced = joined.count("'") % 2 == 0 and joined.count('"') % 2 == 0
        if not cont and in_loop == 0 and balanced:
            cmds.append(cur)
            cur = []
            if len(cmds) >= max_cmds:
                break
    out = []
    for c in cmds:
        line = join_cmd(c)
        if not re.search(r"\bcurl\b", line):
            continue  # only real curl demos render cleanly (excludes grpcurl etc.)
        undef = [v for v in UNDEF_VAR.findall(line) if v not in ALLOWED_VARS]
        if undef:
            return []  # needs shell setup we don't provide; skip the example
        out.append(line)
    return out


def join_cmd(lines):
    """Join a multi-line command unit into a single runnable line."""
    parts = []
    for ln in lines:
        ln = ln.rstrip()
        if ln.endswith("\\"):
            ln = ln[:-1].rstrip()
        parts.append(ln)
    # for-loops: join with '; ' so they run on one line.
    s = " ".join(parts)
    s = re.sub(r"\s+", " ", s).strip()
    # Ensure shell separators survive the line join: '...; do', '...; done'.
    s = re.sub(r";?\s*\bdo\b", "; do", s, count=1)
    s = re.sub(r";?\s+done\b", "; done", s)
    for pat, repl in MODEL_FIXES:
        s = pat.sub(repl, s)
    return s


def fix_models_in_file(path):
    with open(path) as f:
        txt = f.read()
    new = txt
    for pat, repl in MODEL_FIXES:
        new = pat.sub(repl, new)
    if new != txt:
        with open(path, "w") as f:
            f.write(new)
        return True
    return False


def is_ai(sb_text):
    return "type: ai_proxy" in sb_text


def tape_for(name, cmds, is_ai_example):
    height = 340 + 130 * min(len(cmds), 2)
    sleep = "3.5s" if is_ai_example else "1.6s"
    lines = [
        f"# sbproxy example cassette: {name}. Auto-generated by scripts/gen-example-tapes.py.",
        f"# Regenerate with: scripts/record-tapes.sh {name}",
        "#",
        f"# CONFIG: examples/{name}/sb.yml",
        "",
        f'Output "docs/assets/{name}.gif"',
        "",
        "Require curl",
        "",
        'Set Shell "bash"',
        "Set FontSize 16",
        "Set Width 1280",
        f"Set Height {height}",
        "Set Padding 24",
        "Set TypingSpeed 30ms",
        f"Set Theme {THEME}",
        "",
        "Hide",
        "Type `export PS1='$ '; clear`",
        "Enter",
        "Show",
        "",
    ]
    for c in cmds:
        c = c.replace("`", "'")  # backtick delimiter safety
        lines.append(f"Type `{c}`")
        lines.append("Enter")
        lines.append(f"Sleep {sleep}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    list_only = "--list" in sys.argv
    os.makedirs(TAPES, exist_ok=True)

    # Remove stale auto-generated tapes (hand-authored headline tapes lack the
    # marker and are preserved) so examples that are now skipped don't keep a
    # dangling tape.
    if not list_only:
        for fn in os.listdir(TAPES):
            p = os.path.join(TAPES, fn)
            if fn.endswith(".tape") and os.path.isfile(p):
                with open(p) as f:
                    if GEN_MARKER in f.read():
                        os.remove(p)

    gen, skip = [], []
    for name in sorted(os.listdir(EXAMPLES)):
        d = os.path.join(EXAMPLES, name)
        sb = os.path.join(d, "sb.yml")
        if not os.path.isfile(sb):
            continue
        if name in HEADLINE:
            skip.append((name, "headline (hand-authored)"))
            continue
        sb_text = open(sb).read()
        if EXTERNAL.search(sb_text):
            skip.append((name, "needs external service"))
            continue
        hdr = header_lines(sb)
        cmds = extract_commands(hdr)
        if not cmds:
            skip.append((name, "no Test: curl block"))
            continue
        if not list_only:
            fix_models_in_file(sb)
        tape = tape_for(name, cmds, is_ai(sb_text))
        if not list_only:
            with open(os.path.join(TAPES, f"{name}.tape"), "w") as f:
                f.write(tape)
        gen.append(name)

    print(f"generate: {len(gen)}")
    print(f"skip: {len(skip)}")
    for n, why in skip:
        print(f"  skip {n}: {why}")
    if list_only:
        print("\n(--list: no files written)")


if __name__ == "__main__":
    main()
