#!/usr/bin/env bash
# Regenerate docs/llms-full.txt: the full SBproxy docs corpus flattened
# into one file so AI tools (Claude, ChatGPT, Cursor, ...) can fetch
# everything in one HTTP round trip per the llmstxt.org convention.
#
# Pairs with docs/llms.txt (the small index). Operators who want a
# specific page still browse the per-doc URLs; AI tools that want the
# whole corpus pull this single file.
#
# Usage:
#   ./scripts/regen-llms-full.sh          # regenerate docs/llms-full.txt
#   ./scripts/regen-llms-full.sh --check  # exit 1 if regen would diff
#
# The file is generated; do not hand-edit. Edit the source `docs/*.md`
# and re-run this script.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT_DIR/docs/llms-full.txt"
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

CHECK_MODE=false
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_MODE=true ;;
    -h|--help) sed -n '1,20p' "$0"; exit 0 ;;
  esac
done

cd "$ROOT_DIR"

GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
if $CHECK_MODE && [ -f "$OUT" ]; then
  existing_generated_at=$(grep -m 1 '^Generated: ' "$OUT" | sed 's/^Generated: //' || true)
  if [ -n "$existing_generated_at" ]; then
    GENERATED_AT="$existing_generated_at"
  fi
fi

# Header. Lists the source URL, the regen script, and a small TOC so
# an AI tool that fetches the file knows what it has.
{
  echo "# SBproxy: full documentation"
  echo ""
  echo "> Concatenation of every Markdown file under \`sbproxy/docs/\` plus the top-level \`README.md\`, \`MIGRATION.md\`, and \`CHANGELOG.md\`. Designed for AI tools (Claude, ChatGPT, Cursor) that want the entire SBproxy corpus in one request per the [llmstxt.org](https://llmstxt.org/) convention."
  echo ""
  echo "Pairs with \`/llms.txt\` (the small AI-discoverable feature catalog at \`docs/llms.txt\`). For per-doc URLs see \`docs/README.md\`."
  echo ""
  echo "Regenerated by \`scripts/regen-llms-full.sh\`. Generated; do not hand-edit."
  echo ""
  echo "Source: https://github.com/soapbucket/sbproxy"
  echo "Generated: $GENERATED_AT"
  echo ""
  echo "---"
  echo ""
  echo "## Table of contents"
  echo ""
  seen_toc=" "
  for f in README.md MIGRATION.md CHANGELOG.md docs/README.md docs/*.md; do
    [ -f "$f" ] || continue
    # Skip llms.txt / llms-full.txt themselves to avoid recursion
    case "$f" in
      docs/llms.txt|docs/llms-full.txt) continue ;;
    esac
    case "$seen_toc" in
      *" $f "*) continue ;;
    esac
    seen_toc="${seen_toc}${f} "
    # Pull the first H1 as the doc's title; fall back to the path.
    title=$(grep -m 1 -E '^# ' "$f" 2>/dev/null | sed 's/^# //' || true)
    [ -z "$title" ] && title="$f"
    echo "- \`$f\`: $title"
  done
  echo ""
  echo "---"
  echo ""

  # Concatenate each doc with a clear separator. Demote the original
  # H1 -> H2 so the file has one H1 (the title above) and each doc
  # becomes a top-level section.
  seen_docs=" "
  for f in README.md MIGRATION.md CHANGELOG.md docs/README.md docs/*.md; do
    [ -f "$f" ] || continue
    case "$f" in
      docs/llms.txt|docs/llms-full.txt) continue ;;
    esac
    case "$seen_docs" in
      *" $f "*) continue ;;
    esac
    seen_docs="${seen_docs}${f} "
    echo ""
    echo "================================================================"
    echo "# $f"
    echo "================================================================"
    echo ""
    # Read the file; demote H1 -> H2 so each doc sits one level under
    # the master file. Keep all other markdown intact.
    sed 's/^# /## /' "$f"
  done
} > "$TMP"

if $CHECK_MODE; then
  if [ -f "$OUT" ] && diff -q "$OUT" "$TMP" >/dev/null 2>&1; then
    echo "docs/llms-full.txt is up to date"
    exit 0
  else
    echo "docs/llms-full.txt is stale; re-run scripts/regen-llms-full.sh" >&2
    exit 1
  fi
else
  mv "$TMP" "$OUT"
  trap - EXIT
  bytes=$(wc -c < "$OUT" | tr -d ' ')
  lines=$(wc -l < "$OUT" | tr -d ' ')
  echo "wrote $OUT ($lines lines, $bytes bytes)"
fi
