// Package middleware contains HTTP middleware for authentication, rate limiting, logging, and request processing.
package middleware

import (
	"net/http"

	"github.com/soapbucket/sbproxy/internal/httpkit/httputil"
	"github.com/soapbucket/sbproxy/internal/request/reqctx"
)

const (
	// maxRequestIDLength is the maximum allowed length for an incoming X-Request-ID header.
	maxRequestIDLength = 128
)

// CorrelationIDMiddleware injects a correlation ID as X-Request-ID on both the
// request (for upstream propagation) and the response (for client correlation).
//
// If the incoming request already carries an X-Request-ID header whose length
// does not exceed maxRequestIDLength, that value is reused. Otherwise the
// internal request ID generated by FastPathMiddleware is used.
//
// The middleware must run after FastPathMiddleware (which initializes RequestData.ID)
// and before the logging middleware so the ID is available for structured logging.
func CorrelationIDMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Determine correlation ID: prefer incoming X-Request-ID if present and valid.
		correlationID := r.Header.Get(httputil.HeaderXRequestID)
		if correlationID == "" || len(correlationID) > maxRequestIDLength {
			// Fall back to the internal request ID set by FastPathMiddleware.
			if rd := reqctx.GetRequestData(r.Context()); rd != nil && rd.ID != "" {
				correlationID = rd.ID
			}
		}

		if correlationID != "" {
			// Set on request for upstream propagation.
			r.Header.Set(httputil.HeaderXRequestID, correlationID)

			// Set on response for client correlation. Use the Header() map directly
			// so the header is present regardless of which handler writes the status.
			w.Header().Set(httputil.HeaderXRequestID, correlationID)
		}

		next.ServeHTTP(w, r)
	})
}
