apiVersion: v1
kind: Service
metadata:
  name: {{ include "soapbucket-proxy.fullname" . }}
  labels:
    {{- include "soapbucket-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "soapbucket-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 8080
    - name: telemetry
      port: {{ .Values.service.telemetryPort }}
      targetPort: 8888
